// Package swift generates Swift reader code from parsed Excel schemas.
package swift

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"iotaexcel/internal/constants"
	"iotaexcel/internal/model"
)

// Options controls Swift code generation.
type Options struct {
	OutputDir string
	Target    string
	Overwrite bool
}

// Generate writes one Swift config file for a workbook and one shared runtime file.
func Generate(wb model.Workbook, opts Options) ([]string, error) {
	runtimeOut := filepath.Join(opts.OutputDir, constants.GeneratedSwiftRuntimeFileName)
	runtimeData := renderRuntime()
	rel := filepath.FromSlash(wb.RelPath)
	dir := filepath.Dir(rel)
	base := strings.TrimSuffix(filepath.Base(rel), filepath.Ext(rel))
	name := base + constants.GeneratedSwiftConfigFileSuffix
	out := filepath.Join(opts.OutputDir, name)
	if dir != "." {
		out = filepath.Join(opts.OutputDir, dir, name)
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return nil, err
	}
	if !opts.Overwrite {
		if _, err := os.Stat(out); err == nil {
			return nil, fmt.Errorf("output exists: %s", out)
		}
	}
	data := render(wb, opts)
	runtimeWritten, err := writeRuntimeFile(runtimeOut, []byte(runtimeData), opts.Overwrite)
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(out, []byte(data), 0o644); err != nil {
		return nil, err
	}
	outputs := []string{out}
	if runtimeWritten {
		outputs = append([]string{runtimeOut}, outputs...)
	}
	return outputs, nil
}

func render(wb model.Workbook, opts Options) string {
	var b strings.Builder
	b.WriteString("// Code generated by iotaexcel. DO NOT EDIT.\n")
	b.WriteString("// Source: " + wb.RelPath + "\n\n")
	b.WriteString("import Foundation\n\n")
	base := strings.TrimSuffix(filepath.Base(filepath.FromSlash(wb.RelPath)), filepath.Ext(wb.RelPath))
	for _, sheet := range wb.Sheets {
		renderTypes(&b, sheet, opts.Target, base)
	}
	return b.String()
}

func renderTypes(b *strings.Builder, sheet model.Sheet, target, workbookName string) {
	typeName := sheet.Name + constants.ConfigSuffix
	tableName := sheet.Name + constants.ConfigTableSuffix
	key := keyField(sheet)
	keyTypeName := swiftType(key.Type)
	keyMethodSuffix := keyMethodName(sheet)
	uniqueFields := uniqueIndexFields(sheet, target)
	bytesFileName := workbookName + "_" + sheet.Name + constants.ConfigSuffix + constants.BytesExtension

	b.WriteString("public struct " + typeName + " {\n")
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		if field.Comment != "" {
			b.WriteString("    // " + sanitizeComment(field.Comment) + "\n")
		}
		b.WriteString("    public var " + field.Name + ": " + swiftType(field.Type) + " = " + swiftDefaultValue(field.Type) + "\n")
	}
	b.WriteString("\n")
	b.WriteString("    public init() {}\n")
	b.WriteString("}\n\n")

	b.WriteString("public final class " + tableName + " {\n")
	b.WriteString("    public let datas: [" + keyTypeName + ": " + typeName + "]\n\n")
	for _, field := range uniqueFields {
		b.WriteString("    private let " + uniqueIndexName(field) + ": [" + swiftType(field.Type) + ": " + typeName + "]\n")
	}
	if len(uniqueFields) > 0 {
		b.WriteString("\n")
	}
	b.WriteString("    public init(datas: [" + keyTypeName + ": " + typeName + "]")
	for _, field := range uniqueFields {
		b.WriteString(", " + uniqueIndexName(field) + ": [" + swiftType(field.Type) + ": " + typeName + "]")
	}
	b.WriteString(") {\n")
	b.WriteString("        self.datas = datas\n")
	for _, field := range uniqueFields {
		b.WriteString("        self." + uniqueIndexName(field) + " = " + uniqueIndexName(field) + "\n")
	}
	b.WriteString("    }\n\n")
	b.WriteString("    public func tryGetBy" + keyMethodSuffix + "(_ key: " + keyTypeName + ") -> " + typeName + "? {\n")
	b.WriteString("        return datas[key]\n")
	b.WriteString("    }\n\n")
	for _, field := range uniqueFields {
		b.WriteString("    public func tryGetBy" + field.Name + "(_ key: " + swiftType(field.Type) + ") -> " + typeName + "? {\n")
		b.WriteString("        return " + uniqueIndexName(field) + "[key]\n")
		b.WriteString("    }\n\n")
	}
	b.WriteString("    public static func load(_ data: Data) throws -> " + tableName + " {\n")
	b.WriteString("        return try load" + tableName + "(data)\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public static func loadFrom(_ readBytes: (String) throws -> Data) throws -> " + tableName + " {\n")
	b.WriteString("        return try load" + tableName + "From(readBytes)\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")

	b.WriteString("public func load" + tableName + "(_ data: Data) throws -> " + tableName + " {\n")
	b.WriteString("    var reader = IotaBytesReader(data: data)\n")
	b.WriteString("    try reader.expectMagic()\n")
	b.WriteString("    let version = try reader.readVarUInt64()\n")
	b.WriteString(fmt.Sprintf("    if version != %d {\n", constants.BytesFormatVersion))
	b.WriteString("        throw IotaBytesError.unsupportedVersion\n")
	b.WriteString("    }\n")
	b.WriteString("    _ = try reader.readString()\n")
	b.WriteString("    _ = try reader.readVarUInt64()\n")
	b.WriteString("    let selfDescribing = try reader.readVarUInt64() != 0\n")
	b.WriteString("    let fieldCount = try reader.readVarUInt64()\n")
	b.WriteString("    for _ in 0..<fieldCount {\n")
	b.WriteString("        _ = try reader.readVarUInt64()\n")
	b.WriteString("        if selfDescribing {\n")
	b.WriteString("            _ = try reader.readString()\n")
	b.WriteString("            _ = try reader.readString()\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	b.WriteString("    let rowCount = try reader.readVarUInt64()\n")
	b.WriteString("    var rows: [" + keyTypeName + ": " + typeName + "] = [:]\n")
	b.WriteString("    rows.reserveCapacity(Int(rowCount))\n")
	for _, field := range uniqueFields {
		b.WriteString("    var " + uniqueIndexName(field) + ": [" + swiftType(field.Type) + ": " + typeName + "] = [:]\n")
		b.WriteString("    " + uniqueIndexName(field) + ".reserveCapacity(Int(rowCount))\n")
	}
	b.WriteString("    for _ in 0..<rowCount {\n")
	b.WriteString("        var rowReader = IotaBytesReader(data: try reader.readBytes())\n")
	b.WriteString("        var row = " + typeName + "()\n")
	b.WriteString("        while !rowReader.end {\n")
	b.WriteString("            let tag = try rowReader.readVarUInt64()\n")
	b.WriteString("            let fieldNo = tag >> 3\n")
	b.WriteString("            let wireType = tag & 7\n")
	b.WriteString("            switch fieldNo {\n")
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		b.WriteString("            case " + fmt.Sprint(field.FieldNo) + ":\n")
		b.WriteString("                row." + field.Name + " = try " + swiftReadExpr(field.Type, "rowReader") + "\n")
	}
	b.WriteString("            default:\n")
	b.WriteString("                try rowReader.skip(wireType: wireType)\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n")
	b.WriteString("        rows[row." + keyName(sheet) + "] = row\n")
	for _, field := range uniqueFields {
		if cond := swiftUniqueIndexCondition(field); cond != "" {
			b.WriteString("        if " + cond + " {\n")
			b.WriteString("            " + uniqueIndexName(field) + "[row." + field.Name + "] = row\n")
			b.WriteString("        }\n")
		} else {
			b.WriteString("        " + uniqueIndexName(field) + "[row." + field.Name + "] = row\n")
		}
	}
	b.WriteString("    }\n")
	b.WriteString("    return " + tableName + "(datas: rows")
	for _, field := range uniqueFields {
		b.WriteString(", " + uniqueIndexName(field) + ": " + uniqueIndexName(field))
	}
	b.WriteString(")\n")
	b.WriteString("}\n\n")
	b.WriteString("public func load" + tableName + "From(_ readBytes: (String) throws -> Data) throws -> " + tableName + " {\n")
	b.WriteString("    return try load" + tableName + "(readBytes(\"" + bytesFileName + "\"))\n")
	b.WriteString("}\n\n")
}

func renderRuntime() string {
	var b strings.Builder
	b.WriteString("// Code generated by iotaexcel. DO NOT EDIT.\n")
	b.WriteString("// Shared .bytes runtime helper.\n\n")
	b.WriteString("import Foundation\n\n")
	b.WriteString("public enum IotaBytesError: Error {\n")
	b.WriteString("    case invalidMagic\n")
	b.WriteString("    case unsupportedVersion\n")
	b.WriteString("    case invalidVarint\n")
	b.WriteString("    case unexpectedEnd\n")
	b.WriteString("    case unsupportedWireType\n")
	b.WriteString("    case lengthTooLarge\n")
	b.WriteString("}\n\n")
	b.WriteString("public struct IotaBytesReader {\n")
	b.WriteString("    private let data: [UInt8]\n")
	b.WriteString("    private var pos: Int = 0\n\n")
	b.WriteString("    public init(data: Data) {\n")
	b.WriteString("        self.data = Array(data)\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public var end: Bool { pos >= data.count }\n\n")
	b.WriteString("    public mutating func expectMagic() throws {\n")
	b.WriteString(fmt.Sprintf("        let magic = try readRaw(%d)\n", len(constants.BytesMagic)))
	b.WriteString(fmt.Sprintf("        if String(bytes: magic, encoding: .ascii) != %q {\n", constants.BytesMagic))
	b.WriteString("            throw IotaBytesError.invalidMagic\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public mutating func readVarUInt64() throws -> UInt64 {\n")
	b.WriteString("        var result: UInt64 = 0\n")
	b.WriteString("        var shift: UInt64 = 0\n")
	b.WriteString("        while true {\n")
	b.WriteString("            let byte = UInt64(try readByte())\n")
	b.WriteString("            result |= (byte & 0x7F) << shift\n")
	b.WriteString("            if (byte & 0x80) == 0 { return result }\n")
	b.WriteString("            shift += 7\n")
	b.WriteString("            if shift > 63 { throw IotaBytesError.invalidVarint }\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public mutating func readSInt64() throws -> Int64 {\n")
	b.WriteString("        let raw = try readVarUInt64()\n")
	b.WriteString("        return Int64(bitPattern: raw >> 1) ^ -Int64(bitPattern: raw & 1)\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public mutating func readSInt32() throws -> Int32 {\n")
	b.WriteString("        return Int32(try readSInt64())\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public mutating func readBool() throws -> Bool {\n")
	b.WriteString("        return try readVarUInt64() != 0\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public mutating func readFloat() throws -> Float {\n")
	b.WriteString("        let raw = try readRaw(4)\n")
	b.WriteString("        let bits = UInt32(raw[0]) | (UInt32(raw[1]) << 8) | (UInt32(raw[2]) << 16) | (UInt32(raw[3]) << 24)\n")
	b.WriteString("        return Float(bitPattern: bits)\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public mutating func readDouble() throws -> Double {\n")
	b.WriteString("        let raw = try readRaw(8)\n")
	b.WriteString("        var bits: UInt64 = 0\n")
	b.WriteString("        for i in 0..<8 { bits |= UInt64(raw[i]) << UInt64(8 * i) }\n")
	b.WriteString("        return Double(bitPattern: bits)\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public mutating func readBytes() throws -> Data {\n")
	b.WriteString("        let size = try readVarUInt64()\n")
	b.WriteString("        if size > UInt64(Int.max) { throw IotaBytesError.lengthTooLarge }\n")
	b.WriteString("        return Data(try readRaw(Int(size)))\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public mutating func readString() throws -> String {\n")
	b.WriteString("        return String(decoding: try readBytes(), as: UTF8.self)\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public mutating func skip(wireType: UInt64) throws {\n")
	b.WriteString("        switch wireType {\n")
	b.WriteString("        case 0: _ = try readVarUInt64()\n")
	b.WriteString("        case 1: _ = try readRaw(8)\n")
	b.WriteString("        case 2: _ = try readBytes()\n")
	b.WriteString("        case 5: _ = try readRaw(4)\n")
	b.WriteString("        default: throw IotaBytesError.unsupportedWireType\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n\n")
	b.WriteString("    private mutating func readByte() throws -> UInt8 {\n")
	b.WriteString("        guard pos < data.count else { throw IotaBytesError.unexpectedEnd }\n")
	b.WriteString("        let value = data[pos]\n")
	b.WriteString("        pos += 1\n")
	b.WriteString("        return value\n")
	b.WriteString("    }\n\n")
	b.WriteString("    private mutating func readRaw(_ size: Int) throws -> [UInt8] {\n")
	b.WriteString("        guard size >= 0, pos + size <= data.count else { throw IotaBytesError.unexpectedEnd }\n")
	b.WriteString("        let out = Array(data[pos..<pos + size])\n")
	b.WriteString("        pos += size\n")
	b.WriteString("        return out\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")
	b.WriteString("public func parseStringList(_ value: String) -> [String] {\n")
	b.WriteString("    return value.isEmpty ? [] : value.split(separator: \"|\", omittingEmptySubsequences: false).map(String.init)\n")
	b.WriteString("}\n\n")
	b.WriteString("public func parseStringMap(_ value: String) -> [String: String] {\n")
	b.WriteString("    var out: [String: String] = [:]\n")
	b.WriteString("    if value.isEmpty { return out }\n")
	b.WriteString("    for entry in value.split(separator: \"|\", omittingEmptySubsequences: false) {\n")
	b.WriteString("        let parts = entry.split(separator: \":\", maxSplits: 1, omittingEmptySubsequences: false)\n")
	b.WriteString("        if parts.count == 2 && !parts[0].isEmpty {\n")
	b.WriteString("            out[String(parts[0])] = String(parts[1])\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	b.WriteString("    return out\n")
	b.WriteString("}\n")
	return b.String()
}

func writeRuntimeFile(path string, data []byte, overwrite bool) (bool, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if existing, err := os.ReadFile(path); err == nil {
		if string(existing) == string(data) {
			return false, nil
		}
		if !overwrite {
			return false, fmt.Errorf("output exists: %s", path)
		}
	}
	return true, os.WriteFile(path, data, 0o644)
}

func includeField(field model.Field, target string) bool {
	if field.Usage == model.UsageComment {
		return false
	}
	switch target {
	case "client":
		return field.Usage == model.UsageClient || field.Usage == model.UsageAll
	case "server":
		return field.Usage == model.UsageServer || field.Usage == model.UsageAll
	default:
		return true
	}
}

func swiftType(typ model.TypeSpec) string {
	switch typ.Kind {
	case model.TypeBool:
		return "Bool"
	case model.TypeInt, model.TypeInt32:
		return "Int32"
	case model.TypeInt64, model.TypeDateTime:
		return "Int64"
	case model.TypeFloat:
		return "Float"
	case model.TypeDouble:
		return "Double"
	case model.TypeBytes:
		return "Data"
	case model.TypeArray:
		return "[String]"
	case model.TypeMap:
		return "[String: String]"
	default:
		return "String"
	}
}

func swiftReadExpr(typ model.TypeSpec, reader string) string {
	switch typ.Kind {
	case model.TypeBool:
		return reader + ".readBool()"
	case model.TypeInt, model.TypeInt32:
		return reader + ".readSInt32()"
	case model.TypeInt64, model.TypeDateTime:
		return reader + ".readSInt64()"
	case model.TypeFloat:
		return reader + ".readFloat()"
	case model.TypeDouble:
		return reader + ".readDouble()"
	case model.TypeBytes:
		return reader + ".readBytes()"
	case model.TypeArray:
		return "parseStringList(" + reader + ".readString())"
	case model.TypeMap:
		return "parseStringMap(" + reader + ".readString())"
	default:
		return reader + ".readString()"
	}
}

func swiftDefaultValue(typ model.TypeSpec) string {
	switch typ.Kind {
	case model.TypeBool:
		return "false"
	case model.TypeInt, model.TypeInt32, model.TypeInt64, model.TypeFloat, model.TypeDouble:
		return "0"
	case model.TypeDateTime:
		return "-62135596800"
	case model.TypeBytes:
		return "Data()"
	case model.TypeArray:
		return "[]"
	case model.TypeMap:
		return "[:]"
	default:
		return "\"\""
	}
}

func keyField(sheet model.Sheet) model.Field {
	for _, field := range sheet.Fields {
		if field.IsKey {
			return field
		}
	}
	return model.Field{Type: model.TypeSpec{Kind: model.TypeString}}
}

func keyName(sheet model.Sheet) string {
	for _, field := range sheet.Fields {
		if field.IsKey {
			return field.Name
		}
	}
	return ""
}

func keyMethodName(sheet model.Sheet) string {
	name := keyName(sheet)
	if name == "" {
		return "Key"
	}
	return name
}

func uniqueIndexFields(sheet model.Sheet, target string) []model.Field {
	fields := []model.Field{}
	for _, field := range sheet.Fields {
		if field.Unique && !field.IsKey && includeField(field, target) {
			fields = append(fields, field)
		}
	}
	return fields
}

func uniqueIndexName(field model.Field) string {
	return field.Name + "Index"
}

func swiftUniqueIndexCondition(field model.Field) string {
	if field.Type.Kind == model.TypeString && !field.Required {
		return "!row." + field.Name + ".isEmpty"
	}
	return ""
}

func sanitizeComment(comment string) string {
	comment = strings.ReplaceAll(comment, "\r", " ")
	comment = strings.ReplaceAll(comment, "\n", " ")
	return comment
}
