// Package csharp 根据解析后的 Excel schema 生成 C# 读取代码。
//
// 生成结果包含 DataConfig 命名空间下的 sheet 类、字段属性、Load(byte[]) 方法，
// 以及独立的 .bytes 读取 runtime helper 文件。
package csharp

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"iotaexcel/internal/constants"
	"iotaexcel/internal/model"
)

// Options 控制 C# 代码生成。
// Namespace 默认是 DataConfig；Target 用于过滤 client/server 字段；Overwrite 控制是否覆盖已有 .cs 文件。
type Options struct {
	OutputDir string
	Namespace string
	Target    string
	Overwrite bool
}

// Generate 为一个 Excel workbook 生成一个 C# 文件，并在输出根目录生成共享 runtime 文件。
// 文件名来自“Excel 文件名 + .config”，sheet 名映射为数据类和 table 类，命名已在 schema 阶段完成标识符校验。
func Generate(wb model.Workbook, opts Options) ([]string, error) {
	if opts.Namespace == "" {
		opts.Namespace = constants.DefaultCSharpNamespace
	}
	runtimeOut := filepath.Join(opts.OutputDir, constants.GeneratedCSharpRuntimeFileName)
	runtimeData := renderRuntime(opts)
	rel := filepath.FromSlash(wb.RelPath)
	dir := filepath.Dir(rel)
	base := strings.TrimSuffix(filepath.Base(rel), filepath.Ext(rel))
	name := base + constants.GeneratedCSharpConfigFileSuffix
	out := filepath.Join(opts.OutputDir, name)
	if dir != "." {
		out = filepath.Join(opts.OutputDir, dir, name)
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return nil, err
	}
	if !opts.Overwrite {
		if _, err := os.Stat(out); err == nil {
			return nil, fmt.Errorf("output exists: %s", out)
		}
	}
	data := render(wb, opts)
	runtimeWritten, err := writeRuntimeFile(runtimeOut, []byte(runtimeData), opts.Overwrite)
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(out, []byte(data), 0o644); err != nil {
		return nil, err
	}
	outputs := []string{out}
	if runtimeWritten {
		outputs = append([]string{runtimeOut}, outputs...)
	}
	return outputs, nil
}

// render 拼接完整 C# 源码文本。
// 业务表文件只包含 sheet 类，通用 runtime helper 由 renderRuntime 单独输出。
func render(wb model.Workbook, opts Options) string {
	var b strings.Builder
	b.WriteString("// <auto-generated>\n")
	b.WriteString("// Generated by iotaexcel. Do not edit manually.\n")
	b.WriteString("// Source: " + wb.RelPath + "\n")
	b.WriteString("// </auto-generated>\n")
	b.WriteString("using System;\n")
	b.WriteString("using System.Collections.Generic;\n")
	b.WriteString("using System.IO;\n")
	b.WriteString("using System.Threading.Tasks;\n")
	b.WriteString("\n")
	b.WriteString("namespace " + opts.Namespace + "\n{\n")
	base := strings.TrimSuffix(filepath.Base(filepath.FromSlash(wb.RelPath)), filepath.Ext(wb.RelPath))
	for _, sheet := range wb.Sheets {
		renderClass(&b, sheet, opts.Target, base)
	}
	b.WriteString("}\n")
	return b.String()
}

// renderClass 生成单个 sheet 对应的数据类和 table 类。
// 数据类命名为 SheetNameConfig；table 类命名为 SheetNameConfigTable，并负责 Load 和 key 查询。
func renderClass(b *strings.Builder, sheet model.Sheet, target, workbookName string) {
	className := sheet.Name + constants.ConfigSuffix
	tableName := sheet.Name + constants.ConfigTableSuffix
	keyTypeName := keyType(sheet)
	keyMethodSuffix := keyMethodName(sheet)
	bytesFileName := workbookName + "_" + sheet.Name + constants.ConfigSuffix + constants.BytesExtension
	b.WriteString("    public sealed class " + className + "\n    {\n")
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		if field.Comment != "" {
			b.WriteString("        /// <summary>" + escapeComment(field.Comment) + "</summary>\n")
		}
		b.WriteString("        public " + csharpType(field.Type) + " " + field.Name + " { get; set; }\n")
	}
	b.WriteString("    }\n\n")

	b.WriteString("    public sealed class " + tableName + "\n    {\n")
	b.WriteString("        private readonly IReadOnlyDictionary<" + keyTypeName + ", " + className + "> datas;\n\n")
	b.WriteString("        private " + tableName + "(IReadOnlyDictionary<" + keyTypeName + ", " + className + "> datas)\n")
	b.WriteString("        {\n")
	b.WriteString("            this.datas = datas;\n")
	b.WriteString("        }\n\n")
	b.WriteString("        public IReadOnlyDictionary<" + keyTypeName + ", " + className + "> Datas => datas;\n\n")
	b.WriteString("        public bool TryGetBy" + keyMethodSuffix + "(" + keyTypeName + " key, out " + className + " value) => datas.TryGetValue(key, out value);\n")
	b.WriteString("\n")
	b.WriteString("        public static " + tableName + " Load(byte[] data)\n")
	b.WriteString("        {\n")
	b.WriteString("            var reader = new IotaBytesReader(data);\n")
	b.WriteString("            reader.ExpectMagic();\n")
	b.WriteString("            var version = reader.ReadVarUInt64();\n")
	b.WriteString(fmt.Sprintf("            if (version != %d)\n", constants.BytesFormatVersion))
	b.WriteString("            {\n")
	b.WriteString("                throw new InvalidDataException(\"Unsupported iotaexcel bytes version.\");\n")
	b.WriteString("            }\n")
	b.WriteString("            var schemaHash = reader.ReadString();\n")
	b.WriteString("            var keyFieldNo = reader.ReadVarUInt64();\n")
	b.WriteString("            var selfDescribing = reader.ReadVarUInt64() != 0;\n")
	b.WriteString("            var fieldCount = reader.ReadVarUInt64();\n")
	b.WriteString("            for (ulong i = 0; i < fieldCount; i++)\n")
	b.WriteString("            {\n")
	b.WriteString("                reader.ReadVarUInt64();\n")
	b.WriteString("                if (selfDescribing)\n")
	b.WriteString("                {\n")
	b.WriteString("                    reader.ReadString();\n")
	b.WriteString("                    reader.ReadString();\n")
	b.WriteString("                }\n")
	b.WriteString("            }\n")
	b.WriteString("            var rowCount = reader.ReadVarUInt64();\n")
	b.WriteString("            var rows = new Dictionary<" + keyTypeName + ", " + className + ">();\n")
	b.WriteString("            for (ulong i = 0; i < rowCount; i++)\n")
	b.WriteString("            {\n")
	b.WriteString("                var rowReader = new IotaBytesReader(reader.ReadBytes());\n")
	b.WriteString("                var row = new " + className + "();\n")
	b.WriteString("                while (!rowReader.End)\n")
	b.WriteString("                {\n")
	b.WriteString("                    var tag = rowReader.ReadVarUInt64();\n")
	b.WriteString("                    var fieldNo = tag >> 3;\n")
	b.WriteString("                    var wireType = tag & 7;\n")
	b.WriteString("                    switch (fieldNo)\n")
	b.WriteString("                    {\n")
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		b.WriteString("                        case " + fmt.Sprint(field.FieldNo) + ":\n")
		b.WriteString("                            row." + field.Name + " = " + csharpReadExpr(field.Type, "rowReader") + ";\n")
		b.WriteString("                            break;\n")
	}
	b.WriteString("                        default:\n")
	b.WriteString("                            rowReader.Skip(wireType);\n")
	b.WriteString("                            break;\n")
	b.WriteString("                    }\n")
	b.WriteString("                }\n")
	b.WriteString("                rows[row." + keyName(sheet) + "] = row;\n")
	b.WriteString("            }\n")
	b.WriteString("            _ = version;\n")
	b.WriteString("            _ = schemaHash;\n")
	b.WriteString("            _ = keyFieldNo;\n")
	b.WriteString("            _ = selfDescribing;\n")
	b.WriteString("            return new " + tableName + "(rows);\n")
	b.WriteString("        }\n")
	b.WriteString("\n")
	b.WriteString("        public static async Task<" + tableName + "> LoadAsync(Func<string, Task<byte[]>> readBytesAsync)\n")
	b.WriteString("        {\n")
	b.WriteString("            if (readBytesAsync == null)\n")
	b.WriteString("            {\n")
	b.WriteString("                throw new ArgumentNullException(nameof(readBytesAsync));\n")
	b.WriteString("            }\n")
	b.WriteString("            return Load(await readBytesAsync(\"" + bytesFileName + "\"));\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n\n")
}

// renderRuntime 生成 C# 侧共享的 .bytes 读取辅助类型。
func renderRuntime(opts Options) string {
	var b strings.Builder
	b.WriteString("// <auto-generated>\n")
	b.WriteString("// Generated by iotaexcel. Do not edit manually.\n")
	b.WriteString("// Shared .bytes runtime helper.\n")
	b.WriteString("// </auto-generated>\n")
	b.WriteString("using System;\n")
	b.WriteString("using System.Collections.Generic;\n")
	b.WriteString("using System.IO;\n")
	b.WriteString("using System.Text;\n\n")
	b.WriteString("namespace " + opts.Namespace + "\n{\n")
	b.WriteString("    internal sealed class IotaBytesReader\n")
	b.WriteString("    {\n")
	b.WriteString("        private readonly byte[] data;\n")
	b.WriteString("        private int pos;\n\n")
	b.WriteString("        public IotaBytesReader(byte[] data)\n")
	b.WriteString("        {\n")
	b.WriteString("            this.data = data;\n")
	b.WriteString("        }\n\n")
	b.WriteString("        public bool End => pos >= data.Length;\n\n")
	b.WriteString("        public void ExpectMagic()\n")
	b.WriteString("        {\n")
	b.WriteString(fmt.Sprintf("            if (Encoding.ASCII.GetString(ReadRaw(%d)) != \"%s\")\n", len(constants.BytesMagic), constants.BytesMagic))
	b.WriteString("            {\n")
	b.WriteString("                throw new InvalidDataException(\"Invalid iotaexcel magic.\");\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n\n")
	b.WriteString("        public ulong ReadVarUInt64()\n")
	b.WriteString("        {\n")
	b.WriteString("            ulong result = 0;\n")
	b.WriteString("            var shift = 0;\n")
	b.WriteString("            while (true)\n")
	b.WriteString("            {\n")
	b.WriteString("                var b = ReadByte();\n")
	b.WriteString("                result |= (ulong)(b & 0x7F) << shift;\n")
	b.WriteString("                if ((b & 0x80) == 0)\n")
	b.WriteString("                {\n")
	b.WriteString("                    return result;\n")
	b.WriteString("                }\n")
	b.WriteString("                shift += 7;\n")
	b.WriteString("                if (shift > 63)\n")
	b.WriteString("                {\n")
	b.WriteString("                    throw new InvalidDataException(\"Invalid varint.\");\n")
	b.WriteString("                }\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n\n")
	b.WriteString("        public long ReadSInt64()\n")
	b.WriteString("        {\n")
	b.WriteString("            var raw = ReadVarUInt64();\n")
	b.WriteString("            return (long)(raw >> 1) ^ -((long)raw & 1);\n")
	b.WriteString("        }\n\n")
	b.WriteString("        public int ReadSInt32() => checked((int)ReadSInt64());\n\n")
	b.WriteString("        public bool ReadBool() => ReadVarUInt64() != 0;\n\n")
	b.WriteString("        public float ReadFloat() => BitConverter.ToSingle(ReadRaw(4), 0);\n\n")
	b.WriteString("        public double ReadDouble() => BitConverter.ToDouble(ReadRaw(8), 0);\n\n")
	b.WriteString("        public byte[] ReadBytes()\n")
	b.WriteString("        {\n")
	b.WriteString("            var size = checked((int)ReadVarUInt64());\n")
	b.WriteString("            return ReadRaw(size);\n")
	b.WriteString("        }\n\n")
	b.WriteString("        public string ReadString() => Encoding.UTF8.GetString(ReadBytes());\n\n")
	b.WriteString("        public void Skip(ulong wireType)\n")
	b.WriteString("        {\n")
	b.WriteString("            switch (wireType)\n")
	b.WriteString("            {\n")
	b.WriteString("                case 0: ReadVarUInt64(); break;\n")
	b.WriteString("                case 1: ReadRaw(8); break;\n")
	b.WriteString("                case 2: ReadBytes(); break;\n")
	b.WriteString("                case 5: ReadRaw(4); break;\n")
	b.WriteString("                default: throw new InvalidDataException($\"Unsupported wire type {wireType}.\");\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n\n")
	b.WriteString("        private byte ReadByte()\n")
	b.WriteString("        {\n")
	b.WriteString("            if (pos >= data.Length) throw new EndOfStreamException();\n")
	b.WriteString("            return data[pos++];\n")
	b.WriteString("        }\n\n")
	b.WriteString("        private byte[] ReadRaw(int size)\n")
	b.WriteString("        {\n")
	b.WriteString("            if (size < 0 || pos + size > data.Length) throw new EndOfStreamException();\n")
	b.WriteString("            var bytes = new byte[size];\n")
	b.WriteString("            Buffer.BlockCopy(data, pos, bytes, 0, size);\n")
	b.WriteString("            pos += size;\n")
	b.WriteString("            return bytes;\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n\n")
	b.WriteString("    internal static class IotaBytesRuntime\n")
	b.WriteString("    {\n")
	b.WriteString("        public static string? StringOrNull(string value)\n")
	b.WriteString("        {\n")
	b.WriteString("            return string.IsNullOrEmpty(value) ? null : value;\n")
	b.WriteString("        }\n\n")
	b.WriteString("        public static List<string>? ParseList(string value)\n")
	b.WriteString("        {\n")
	b.WriteString("            if (string.IsNullOrEmpty(value))\n")
	b.WriteString("            {\n")
	b.WriteString("                return null;\n")
	b.WriteString("            }\n")
	b.WriteString("            return new List<string>(value.Split(new[] { '|' }, StringSplitOptions.RemoveEmptyEntries));\n")
	b.WriteString("        }\n\n")
	b.WriteString("        public static Dictionary<string, string>? ParseMap(string value)\n")
	b.WriteString("        {\n")
	b.WriteString("            if (string.IsNullOrEmpty(value))\n")
	b.WriteString("            {\n")
	b.WriteString("                return null;\n")
	b.WriteString("            }\n")
	b.WriteString("            var result = new Dictionary<string, string>();\n")
	b.WriteString("            foreach (var entry in value.Split('|'))\n")
	b.WriteString("            {\n")
	b.WriteString("                var index = entry.IndexOf(':');\n")
	b.WriteString("                if (index <= 0) continue;\n")
	b.WriteString("                result[entry.Substring(0, index)] = entry.Substring(index + 1);\n")
	b.WriteString("            }\n")
	b.WriteString("            return result;\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String()
}

// writeRuntimeFile 写出共享 runtime。多个 workbook 批量 codegen 时会重复调用：
// 已存在且内容一致时直接复用，避免未开启 overwrite 时第二个 workbook 失败。
func writeRuntimeFile(path string, data []byte, overwrite bool) (bool, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if existing, err := os.ReadFile(path); err == nil {
		if string(existing) == string(data) {
			return false, nil
		}
		if !overwrite {
			return false, fmt.Errorf("output exists: %s", path)
		}
	}
	return true, os.WriteFile(path, data, 0o644)
}

// includeField 判断字段是否应该出现在生成代码中。
// comment 字段不生成属性；client/server 目标只生成对应字段和 all 字段。
func includeField(field model.Field, target string) bool {
	if field.Usage == model.UsageComment {
		return false
	}
	switch target {
	case "client":
		return field.Usage == model.UsageClient || field.Usage == model.UsageAll
	case "server":
		return field.Usage == model.UsageServer || field.Usage == model.UsageAll
	default:
		return true
	}
}

// csharpType 把内部 TypeSpec 映射为 C# 属性类型。
// array/map/ref 当前按 MVP 文本载荷还原为 List<string>?、Dictionary<string,string>? 和 string?。
func csharpType(typ model.TypeSpec) string {
	switch typ.Kind {
	case model.TypeBool:
		return "bool"
	case model.TypeInt, model.TypeInt32:
		return "int"
	case model.TypeInt64, model.TypeDateTime:
		return "long"
	case model.TypeFloat:
		return "float"
	case model.TypeDouble:
		return "double"
	case model.TypeBytes:
		return "byte[]"
	case model.TypeArray:
		return "List<string>?"
	case model.TypeMap:
		return "Dictionary<string, string>?"
	case model.TypeRef:
		return "string?"
	default:
		return "string"
	}
}

// csharpReadExpr 生成某个字段从 rowReader 读取值的 C# 表达式。
// 该表达式必须和 binary.go 中的 wireType/值编码保持一致。
func csharpReadExpr(typ model.TypeSpec, reader string) string {
	switch typ.Kind {
	case model.TypeBool:
		return reader + ".ReadBool()"
	case model.TypeInt, model.TypeInt32:
		return reader + ".ReadSInt32()"
	case model.TypeInt64, model.TypeDateTime:
		return reader + ".ReadSInt64()"
	case model.TypeFloat:
		return reader + ".ReadFloat()"
	case model.TypeDouble:
		return reader + ".ReadDouble()"
	case model.TypeBytes:
		return reader + ".ReadBytes()"
	case model.TypeArray:
		return "IotaBytesRuntime.ParseList(" + reader + ".ReadString())"
	case model.TypeMap:
		return "IotaBytesRuntime.ParseMap(" + reader + ".ReadString())"
	case model.TypeRef:
		return "IotaBytesRuntime.StringOrNull(" + reader + ".ReadString())"
	default:
		return reader + ".ReadString()"
	}
}

// keyType 返回 sheet 唯一 key 在 C# 中的类型。
// schema 层已经限制 key 只能是 int/int32/int64/string。
func keyType(sheet model.Sheet) string {
	for _, field := range sheet.Fields {
		if field.IsKey {
			return csharpType(field.Type)
		}
	}
	return "string"
}

// keyName 返回 sheet 唯一 key 的字段名。
// Load 方法会通过 row.<keyName> 把每行数据写入字典。
func keyName(sheet model.Sheet) string {
	for _, field := range sheet.Fields {
		if field.IsKey {
			return field.Name
		}
	}
	return ""
}

// keyMethodName 返回用于 TryGetByX 的 key 字段后缀。
// 字段名已通过标识符校验，按 Excel 中的字段名原样拼接。
func keyMethodName(sheet model.Sheet) string {
	name := keyName(sheet)
	if name == "" {
		return "Key"
	}
	return name
}

// escapeComment 转义 XML 文档注释中的特殊字符。
// Excel 第 4 行字段注释会写入 <summary>，因此需要避免破坏 C# XML 注释结构。
func escapeComment(comment string) string {
	comment = strings.ReplaceAll(comment, "&", "&amp;")
	comment = strings.ReplaceAll(comment, "<", "&lt;")
	comment = strings.ReplaceAll(comment, ">", "&gt;")
	return comment
}
