// Package cpp generates C++ reader code from parsed Excel schemas.
package cpp

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"iotaexcel/internal/constants"
	"iotaexcel/internal/model"
)

// Options controls C++ code generation.
type Options struct {
	OutputDir string
	Namespace string
	Target    string
	Overwrite bool
}

// Generate writes one C++ config header for a workbook and one shared runtime header.
func Generate(wb model.Workbook, opts Options) ([]string, error) {
	if opts.Namespace == "" {
		opts.Namespace = constants.DefaultCppNamespace
	}
	runtimeOut := filepath.Join(opts.OutputDir, constants.GeneratedCppRuntimeFileName)
	runtimeData := renderRuntime(opts)
	rel := filepath.FromSlash(wb.RelPath)
	dir := filepath.Dir(rel)
	base := strings.TrimSuffix(filepath.Base(rel), filepath.Ext(rel))
	name := base + constants.GeneratedCppConfigFileSuffix
	out := filepath.Join(opts.OutputDir, name)
	if dir != "." {
		out = filepath.Join(opts.OutputDir, dir, name)
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return nil, err
	}
	if !opts.Overwrite {
		if _, err := os.Stat(out); err == nil {
			return nil, fmt.Errorf("output exists: %s", out)
		}
	}
	data := render(wb, opts)
	runtimeWritten, err := writeRuntimeFile(runtimeOut, []byte(runtimeData), opts.Overwrite)
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(out, []byte(data), 0o644); err != nil {
		return nil, err
	}
	outputs := []string{out}
	if runtimeWritten {
		outputs = append([]string{runtimeOut}, outputs...)
	}
	return outputs, nil
}

func render(wb model.Workbook, opts Options) string {
	var b strings.Builder
	b.WriteString("// Code generated by iotaexcel. DO NOT EDIT.\n")
	b.WriteString("// Source: " + wb.RelPath + "\n")
	b.WriteString("#pragma once\n\n")
	b.WriteString("#include \"iotaexcel_runtime.hpp\"\n\n")
	b.WriteString("#include <cstdint>\n")
	b.WriteString("#include <functional>\n")
	b.WriteString("#include <string>\n")
	b.WriteString("#include <unordered_map>\n")
	b.WriteString("#include <utility>\n")
	b.WriteString("#include <vector>\n\n")
	b.WriteString("namespace " + opts.Namespace + " {\n\n")
	base := strings.TrimSuffix(filepath.Base(filepath.FromSlash(wb.RelPath)), filepath.Ext(wb.RelPath))
	for _, sheet := range wb.Sheets {
		renderTypes(&b, sheet, opts.Target, base)
	}
	b.WriteString("} // namespace " + opts.Namespace + "\n")
	return b.String()
}

func renderTypes(b *strings.Builder, sheet model.Sheet, target, workbookName string) {
	typeName := sheet.Name + constants.ConfigSuffix
	tableName := sheet.Name + constants.ConfigTableSuffix
	keyTypeName := cppType(keyField(sheet).Type)
	keyMethodSuffix := keyMethodName(sheet)
	uniqueFields := uniqueIndexFields(sheet, target)
	bytesFileName := workbookName + "_" + sheet.Name + constants.ConfigSuffix + constants.BytesExtension

	b.WriteString("struct " + typeName + " {\n")
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		if field.Comment != "" {
			b.WriteString("    // " + sanitizeComment(field.Comment) + "\n")
		}
		b.WriteString("    " + cppType(field.Type) + " " + field.Name + "{};\n")
	}
	b.WriteString("};\n\n")

	b.WriteString("class " + tableName + " {\n")
	b.WriteString("public:\n")
	b.WriteString("    using KeyType = " + keyTypeName + ";\n")
	b.WriteString("    using DataMap = std::unordered_map<KeyType, " + typeName + ">;\n\n")
	b.WriteString("    explicit " + tableName + "(DataMap datas) : datas_(std::move(datas)) {\n")
	for _, field := range uniqueFields {
		b.WriteString("        " + uniqueIndexName(field) + "_.reserve(datas_.size());\n")
	}
	if len(uniqueFields) > 0 {
		b.WriteString("        for (const auto& entry : datas_) {\n")
		b.WriteString("            const auto& row = entry.second;\n")
		for _, field := range uniqueFields {
			if cond := cppUniqueIndexCondition(field); cond != "" {
				b.WriteString("            if (" + cond + ") {\n")
				b.WriteString("                " + uniqueIndexName(field) + "_.emplace(row." + field.Name + ", entry.first);\n")
				b.WriteString("            }\n")
			} else {
				b.WriteString("            " + uniqueIndexName(field) + "_.emplace(row." + field.Name + ", entry.first);\n")
			}
		}
		b.WriteString("        }\n")
	}
	b.WriteString("    }\n\n")
	b.WriteString("    const DataMap& Datas() const { return datas_; }\n\n")
	b.WriteString("    bool TryGetBy" + keyMethodSuffix + "(const KeyType& key, const " + typeName + "*& value) const {\n")
	b.WriteString("        auto it = datas_.find(key);\n")
	b.WriteString("        if (it == datas_.end()) {\n")
	b.WriteString("            value = nullptr;\n")
	b.WriteString("            return false;\n")
	b.WriteString("        }\n")
	b.WriteString("        value = &it->second;\n")
	b.WriteString("        return true;\n")
	b.WriteString("    }\n\n")
	for _, field := range uniqueFields {
		b.WriteString("    bool TryGetBy" + field.Name + "(const " + cppType(field.Type) + "& key, const " + typeName + "*& value) const {\n")
		b.WriteString("        auto it = " + uniqueIndexName(field) + "_.find(key);\n")
		b.WriteString("        if (it == " + uniqueIndexName(field) + "_.end()) {\n")
		b.WriteString("            value = nullptr;\n")
		b.WriteString("            return false;\n")
		b.WriteString("        }\n")
		b.WriteString("        auto dataIt = datas_.find(it->second);\n")
		b.WriteString("        if (dataIt == datas_.end()) {\n")
		b.WriteString("            value = nullptr;\n")
		b.WriteString("            return false;\n")
		b.WriteString("        }\n")
		b.WriteString("        value = &dataIt->second;\n")
		b.WriteString("        return true;\n")
		b.WriteString("    }\n\n")
	}
	b.WriteString("    static " + tableName + " Load(const std::vector<std::uint8_t>& data) {\n")
	b.WriteString("        IotaBytesReader reader(data);\n")
	b.WriteString("        reader.ExpectMagic();\n")
	b.WriteString("        const auto version = reader.ReadVarUInt64();\n")
	b.WriteString(fmt.Sprintf("        if (version != %d) {\n", constants.BytesFormatVersion))
	b.WriteString("            throw std::runtime_error(\"Unsupported iotaexcel bytes version.\");\n")
	b.WriteString("        }\n")
	b.WriteString("        (void)reader.ReadString();\n")
	b.WriteString("        (void)reader.ReadVarUInt64();\n")
	b.WriteString("        const bool selfDescribing = reader.ReadVarUInt64() != 0;\n")
	b.WriteString("        const auto fieldCount = reader.ReadVarUInt64();\n")
	b.WriteString("        for (std::uint64_t i = 0; i < fieldCount; ++i) {\n")
	b.WriteString("            (void)reader.ReadVarUInt64();\n")
	b.WriteString("            if (selfDescribing) {\n")
	b.WriteString("                (void)reader.ReadString();\n")
	b.WriteString("                (void)reader.ReadString();\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n")
	b.WriteString("        const auto rowCount = reader.ReadVarUInt64();\n")
	b.WriteString("        DataMap rows;\n")
	b.WriteString("        rows.reserve(static_cast<std::size_t>(rowCount));\n")
	b.WriteString("        for (std::uint64_t i = 0; i < rowCount; ++i) {\n")
	b.WriteString("            IotaBytesReader rowReader(reader.ReadBytes());\n")
	b.WriteString("            " + typeName + " row{};\n")
	b.WriteString("            while (!rowReader.End()) {\n")
	b.WriteString("                const auto tag = rowReader.ReadVarUInt64();\n")
	b.WriteString("                const auto fieldNo = tag >> 3;\n")
	b.WriteString("                const auto wireType = tag & 7;\n")
	b.WriteString("                switch (fieldNo) {\n")
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		b.WriteString("                case " + fmt.Sprint(field.FieldNo) + ":\n")
		b.WriteString("                    row." + field.Name + " = " + cppReadExpr(field.Type, "rowReader") + ";\n")
		b.WriteString("                    break;\n")
	}
	b.WriteString("                default:\n")
	b.WriteString("                    rowReader.Skip(wireType);\n")
	b.WriteString("                    break;\n")
	b.WriteString("                }\n")
	b.WriteString("            }\n")
	b.WriteString("            rows.emplace(row." + keyName(sheet) + ", std::move(row));\n")
	b.WriteString("        }\n")
	b.WriteString("        return " + tableName + "(std::move(rows));\n")
	b.WriteString("    }\n\n")
	b.WriteString("    static " + tableName + " LoadFrom(const std::function<std::vector<std::uint8_t>(const std::string&)>& readBytes) {\n")
	b.WriteString("        if (!readBytes) {\n")
	b.WriteString("            throw std::invalid_argument(\"readBytes is empty\");\n")
	b.WriteString("        }\n")
	b.WriteString("        return Load(readBytes(\"" + bytesFileName + "\"));\n")
	b.WriteString("    }\n\n")
	b.WriteString("private:\n")
	b.WriteString("    DataMap datas_;\n")
	for _, field := range uniqueFields {
		b.WriteString("    std::unordered_map<" + cppType(field.Type) + ", KeyType> " + uniqueIndexName(field) + "_;\n")
	}
	b.WriteString("};\n\n")
}

func renderRuntime(opts Options) string {
	var b strings.Builder
	b.WriteString("// Code generated by iotaexcel. DO NOT EDIT.\n")
	b.WriteString("// Shared .bytes runtime helper.\n")
	b.WriteString("#pragma once\n\n")
	b.WriteString("#include <cstdint>\n")
	b.WriteString("#include <cstring>\n")
	b.WriteString("#include <limits>\n")
	b.WriteString("#include <stdexcept>\n")
	b.WriteString("#include <string>\n")
	b.WriteString("#include <unordered_map>\n")
	b.WriteString("#include <utility>\n")
	b.WriteString("#include <vector>\n\n")
	b.WriteString("namespace " + opts.Namespace + " {\n\n")
	b.WriteString("class IotaBytesReader {\n")
	b.WriteString("public:\n")
	b.WriteString("    explicit IotaBytesReader(std::vector<std::uint8_t> data) : owned_(std::move(data)), data_(owned_.data()), size_(owned_.size()) {}\n")
	b.WriteString("    explicit IotaBytesReader(const std::vector<std::uint8_t>& data) : data_(data.data()), size_(data.size()) {}\n\n")
	b.WriteString("    bool End() const { return pos_ >= size_; }\n\n")
	b.WriteString("    void ExpectMagic() {\n")
	b.WriteString(fmt.Sprintf("        const auto magic = ReadRaw(%d);\n", len(constants.BytesMagic)))
	b.WriteString(fmt.Sprintf("        if (std::string(reinterpret_cast<const char*>(magic.data()), magic.size()) != %q) {\n", constants.BytesMagic))
	b.WriteString("            throw std::runtime_error(\"Invalid iotaexcel magic.\");\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n\n")
	b.WriteString("    std::uint64_t ReadVarUInt64() {\n")
	b.WriteString("        std::uint64_t result = 0;\n")
	b.WriteString("        int shift = 0;\n")
	b.WriteString("        while (true) {\n")
	b.WriteString("            const auto byte = ReadByte();\n")
	b.WriteString("            result |= static_cast<std::uint64_t>(byte & 0x7F) << shift;\n")
	b.WriteString("            if ((byte & 0x80) == 0) {\n")
	b.WriteString("                return result;\n")
	b.WriteString("            }\n")
	b.WriteString("            shift += 7;\n")
	b.WriteString("            if (shift > 63) {\n")
	b.WriteString("                throw std::runtime_error(\"Invalid varint.\");\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n\n")
	b.WriteString("    std::int64_t ReadSInt64() {\n")
	b.WriteString("        const auto raw = ReadVarUInt64();\n")
	b.WriteString("        return static_cast<std::int64_t>(raw >> 1) ^ -static_cast<std::int64_t>(raw & 1);\n")
	b.WriteString("    }\n\n")
	b.WriteString("    std::int32_t ReadSInt32() { return static_cast<std::int32_t>(ReadSInt64()); }\n")
	b.WriteString("    bool ReadBool() { return ReadVarUInt64() != 0; }\n\n")
	b.WriteString("    float ReadFloat() {\n")
	b.WriteString("        const auto data = ReadRaw(4);\n")
	b.WriteString("        std::uint32_t bits = static_cast<std::uint32_t>(data[0]) |\n")
	b.WriteString("            (static_cast<std::uint32_t>(data[1]) << 8) |\n")
	b.WriteString("            (static_cast<std::uint32_t>(data[2]) << 16) |\n")
	b.WriteString("            (static_cast<std::uint32_t>(data[3]) << 24);\n")
	b.WriteString("        float value;\n")
	b.WriteString("        std::memcpy(&value, &bits, sizeof(value));\n")
	b.WriteString("        return value;\n")
	b.WriteString("    }\n\n")
	b.WriteString("    double ReadDouble() {\n")
	b.WriteString("        const auto data = ReadRaw(8);\n")
	b.WriteString("        std::uint64_t bits = 0;\n")
	b.WriteString("        for (int i = 0; i < 8; ++i) {\n")
	b.WriteString("            bits |= static_cast<std::uint64_t>(data[static_cast<std::size_t>(i)]) << (8 * i);\n")
	b.WriteString("        }\n")
	b.WriteString("        double value;\n")
	b.WriteString("        std::memcpy(&value, &bits, sizeof(value));\n")
	b.WriteString("        return value;\n")
	b.WriteString("    }\n\n")
	b.WriteString("    std::vector<std::uint8_t> ReadBytes() {\n")
	b.WriteString("        const auto size = ReadVarUInt64();\n")
	b.WriteString("        if (size > static_cast<std::uint64_t>(std::numeric_limits<std::size_t>::max())) {\n")
	b.WriteString("            throw std::runtime_error(\"Length-delimited value is too large.\");\n")
	b.WriteString("        }\n")
	b.WriteString("        return ReadRaw(static_cast<std::size_t>(size));\n")
	b.WriteString("    }\n\n")
	b.WriteString("    std::string ReadString() {\n")
	b.WriteString("        const auto data = ReadBytes();\n")
	b.WriteString("        return std::string(reinterpret_cast<const char*>(data.data()), data.size());\n")
	b.WriteString("    }\n\n")
	b.WriteString("    void Skip(std::uint64_t wireType) {\n")
	b.WriteString("        switch (wireType) {\n")
	b.WriteString("        case 0: (void)ReadVarUInt64(); break;\n")
	b.WriteString("        case 1: (void)ReadRaw(8); break;\n")
	b.WriteString("        case 2: (void)ReadBytes(); break;\n")
	b.WriteString("        case 5: (void)ReadRaw(4); break;\n")
	b.WriteString("        default: throw std::runtime_error(\"Unsupported wire type.\");\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n\n")
	b.WriteString("private:\n")
	b.WriteString("    std::uint8_t ReadByte() {\n")
	b.WriteString("        if (pos_ >= size_) {\n")
	b.WriteString("            throw std::runtime_error(\"Unexpected end of iotaexcel bytes.\");\n")
	b.WriteString("        }\n")
	b.WriteString("        return data_[pos_++];\n")
	b.WriteString("    }\n\n")
	b.WriteString("    std::vector<std::uint8_t> ReadRaw(std::size_t size) {\n")
	b.WriteString("        if (size > size_ - pos_) {\n")
	b.WriteString("            throw std::runtime_error(\"Unexpected end of iotaexcel bytes.\");\n")
	b.WriteString("        }\n")
	b.WriteString("        std::vector<std::uint8_t> out(data_ + pos_, data_ + pos_ + size);\n")
	b.WriteString("        pos_ += size;\n")
	b.WriteString("        return out;\n")
	b.WriteString("    }\n\n")
	b.WriteString("    std::vector<std::uint8_t> owned_;\n")
	b.WriteString("    const std::uint8_t* data_ = nullptr;\n")
	b.WriteString("    std::size_t size_ = 0;\n")
	b.WriteString("    std::size_t pos_ = 0;\n")
	b.WriteString("};\n\n")
	b.WriteString("inline std::vector<std::string> ParseStringList(const std::string& value) {\n")
	b.WriteString("    std::vector<std::string> result;\n")
	b.WriteString("    if (value.empty()) {\n")
	b.WriteString("        return result;\n")
	b.WriteString("    }\n")
	b.WriteString("    std::size_t start = 0;\n")
	b.WriteString("    while (start <= value.size()) {\n")
	b.WriteString("        const auto end = value.find('|', start);\n")
	b.WriteString("        if (end == std::string::npos) {\n")
	b.WriteString("            result.push_back(value.substr(start));\n")
	b.WriteString("            break;\n")
	b.WriteString("        }\n")
	b.WriteString("        result.push_back(value.substr(start, end - start));\n")
	b.WriteString("        start = end + 1;\n")
	b.WriteString("    }\n")
	b.WriteString("    return result;\n")
	b.WriteString("}\n\n")
	b.WriteString("inline std::unordered_map<std::string, std::string> ParseStringMap(const std::string& value) {\n")
	b.WriteString("    std::unordered_map<std::string, std::string> result;\n")
	b.WriteString("    if (value.empty()) {\n")
	b.WriteString("        return result;\n")
	b.WriteString("    }\n")
	b.WriteString("    std::size_t start = 0;\n")
	b.WriteString("    while (start <= value.size()) {\n")
	b.WriteString("        const auto end = value.find('|', start);\n")
	b.WriteString("        const auto entry = end == std::string::npos ? value.substr(start) : value.substr(start, end - start);\n")
	b.WriteString("        const auto colon = entry.find(':');\n")
	b.WriteString("        if (colon != std::string::npos && colon > 0) {\n")
	b.WriteString("            result[entry.substr(0, colon)] = entry.substr(colon + 1);\n")
	b.WriteString("        }\n")
	b.WriteString("        if (end == std::string::npos) {\n")
	b.WriteString("            break;\n")
	b.WriteString("        }\n")
	b.WriteString("        start = end + 1;\n")
	b.WriteString("    }\n")
	b.WriteString("    return result;\n")
	b.WriteString("}\n\n")
	b.WriteString("} // namespace " + opts.Namespace + "\n")
	return b.String()
}

func writeRuntimeFile(path string, data []byte, overwrite bool) (bool, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if existing, err := os.ReadFile(path); err == nil {
		if string(existing) == string(data) {
			return false, nil
		}
		if !overwrite {
			return false, fmt.Errorf("output exists: %s", path)
		}
	}
	return true, os.WriteFile(path, data, 0o644)
}

func includeField(field model.Field, target string) bool {
	if field.Usage == model.UsageComment {
		return false
	}
	switch target {
	case "client":
		return field.Usage == model.UsageClient || field.Usage == model.UsageAll
	case "server":
		return field.Usage == model.UsageServer || field.Usage == model.UsageAll
	default:
		return true
	}
}

func cppType(typ model.TypeSpec) string {
	switch typ.Kind {
	case model.TypeBool:
		return "bool"
	case model.TypeInt, model.TypeInt32:
		return "std::int32_t"
	case model.TypeInt64, model.TypeDateTime:
		return "std::int64_t"
	case model.TypeFloat:
		return "float"
	case model.TypeDouble:
		return "double"
	case model.TypeBytes:
		return "std::vector<std::uint8_t>"
	case model.TypeArray:
		return "std::vector<std::string>"
	case model.TypeMap:
		return "std::unordered_map<std::string, std::string>"
	default:
		return "std::string"
	}
}

func cppReadExpr(typ model.TypeSpec, reader string) string {
	switch typ.Kind {
	case model.TypeBool:
		return reader + ".ReadBool()"
	case model.TypeInt, model.TypeInt32:
		return reader + ".ReadSInt32()"
	case model.TypeInt64, model.TypeDateTime:
		return reader + ".ReadSInt64()"
	case model.TypeFloat:
		return reader + ".ReadFloat()"
	case model.TypeDouble:
		return reader + ".ReadDouble()"
	case model.TypeBytes:
		return reader + ".ReadBytes()"
	case model.TypeArray:
		return "ParseStringList(" + reader + ".ReadString())"
	case model.TypeMap:
		return "ParseStringMap(" + reader + ".ReadString())"
	default:
		return reader + ".ReadString()"
	}
}

func keyField(sheet model.Sheet) model.Field {
	for _, field := range sheet.Fields {
		if field.IsKey {
			return field
		}
	}
	return model.Field{Type: model.TypeSpec{Kind: model.TypeString}}
}

func keyName(sheet model.Sheet) string {
	for _, field := range sheet.Fields {
		if field.IsKey {
			return field.Name
		}
	}
	return ""
}

func keyMethodName(sheet model.Sheet) string {
	name := keyName(sheet)
	if name == "" {
		return "Key"
	}
	return name
}

func uniqueIndexFields(sheet model.Sheet, target string) []model.Field {
	fields := []model.Field{}
	for _, field := range sheet.Fields {
		if field.Unique && !field.IsKey && includeField(field, target) {
			fields = append(fields, field)
		}
	}
	return fields
}

func uniqueIndexName(field model.Field) string {
	return field.Name + "Index"
}

func cppUniqueIndexCondition(field model.Field) string {
	if field.Type.Kind == model.TypeString && !field.Required {
		return "!row." + field.Name + ".empty()"
	}
	return ""
}

func sanitizeComment(comment string) string {
	comment = strings.ReplaceAll(comment, "\r", " ")
	comment = strings.ReplaceAll(comment, "\n", " ")
	return comment
}
