// Package python generates Python reader code from parsed Excel schemas.
package python

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"iotaexcel/internal/constants"
	"iotaexcel/internal/model"
)

// Options controls Python code generation.
type Options struct {
	OutputDir string
	Target    string
	Overwrite bool
}

// Generate writes one Python config module for a workbook and one shared runtime file.
func Generate(wb model.Workbook, opts Options) ([]string, error) {
	runtimeOut := filepath.Join(opts.OutputDir, constants.GeneratedPythonRuntimeFileName)
	runtimeData := renderRuntime()
	rel := filepath.FromSlash(wb.RelPath)
	dir := filepath.Dir(rel)
	base := strings.TrimSuffix(filepath.Base(rel), filepath.Ext(rel))
	name := base + constants.GeneratedPythonConfigFileSuffix
	out := filepath.Join(opts.OutputDir, name)
	if dir != "." {
		out = filepath.Join(opts.OutputDir, dir, name)
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return nil, err
	}
	if !opts.Overwrite {
		if _, err := os.Stat(out); err == nil {
			return nil, fmt.Errorf("output exists: %s", out)
		}
	}
	data := render(wb, opts)
	runtimeWritten, err := writeRuntimeFile(runtimeOut, []byte(runtimeData), opts.Overwrite)
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(out, []byte(data), 0o644); err != nil {
		return nil, err
	}
	outputs := []string{out}
	if runtimeWritten {
		outputs = append([]string{runtimeOut}, outputs...)
	}
	return outputs, nil
}

func render(wb model.Workbook, opts Options) string {
	var b strings.Builder
	b.WriteString("# Code generated by iotaexcel. DO NOT EDIT.\n")
	b.WriteString("# Source: " + wb.RelPath + "\n\n")
	b.WriteString("from __future__ import annotations\n\n")
	b.WriteString("from dataclasses import dataclass, field\n")
	b.WriteString("from typing import Callable\n\n")
	b.WriteString("from iotaexcel_runtime import IotaBytesReader, parse_string_list, parse_string_map\n\n\n")
	base := strings.TrimSuffix(filepath.Base(filepath.FromSlash(wb.RelPath)), filepath.Ext(wb.RelPath))
	for _, sheet := range wb.Sheets {
		renderTypes(&b, sheet, opts.Target, base)
	}
	return b.String()
}

func renderTypes(b *strings.Builder, sheet model.Sheet, target, workbookName string) {
	typeName := sheet.Name + constants.ConfigSuffix
	tableName := sheet.Name + constants.ConfigTableSuffix
	keyTypeName := pythonType(keyField(sheet).Type)
	keyMethodSuffix := pythonMethodSuffix(keyName(sheet))
	uniqueFields := uniqueIndexFields(sheet, target)
	loadName := pythonLoadFunctionName(tableName)
	bytesFileName := workbookName + "_" + sheet.Name + constants.ConfigSuffix + constants.BytesExtension

	b.WriteString("@dataclass\n")
	b.WriteString("class " + typeName + ":\n")
	wroteField := false
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		if field.Comment != "" {
			b.WriteString("    # " + sanitizeComment(field.Comment) + "\n")
		}
		b.WriteString("    " + field.Name + ": " + pythonType(field.Type) + " = " + pythonDefaultValue(field.Type) + "\n")
		wroteField = true
	}
	if !wroteField {
		b.WriteString("    pass\n")
	}
	b.WriteString("\n\n")

	b.WriteString("class " + tableName + ":\n")
	b.WriteString("    def __init__(self, datas: dict[" + keyTypeName + ", " + typeName + "]")
	for _, field := range uniqueFields {
		b.WriteString(", " + uniqueIndexName(field) + ": dict[" + pythonType(field.Type) + ", " + typeName + "]")
	}
	b.WriteString(") -> None:\n")
	b.WriteString("        self.datas = datas\n\n")
	for _, field := range uniqueFields {
		b.WriteString("        self." + uniqueIndexName(field) + " = " + uniqueIndexName(field) + "\n")
	}
	if len(uniqueFields) > 0 {
		b.WriteString("\n")
	}
	b.WriteString("    def try_get_by_" + keyMethodSuffix + "(self, key: " + keyTypeName + ") -> " + typeName + " | None:\n")
	b.WriteString("        return self.datas.get(key)\n\n")
	for _, field := range uniqueFields {
		b.WriteString("    def try_get_by_" + pythonMethodSuffix(field.Name) + "(self, key: " + pythonType(field.Type) + ") -> " + typeName + " | None:\n")
		b.WriteString("        return self." + uniqueIndexName(field) + ".get(key)\n\n")
	}
	b.WriteString("    @staticmethod\n")
	b.WriteString("    def load(data: bytes | bytearray | memoryview) -> \"" + tableName + "\":\n")
	b.WriteString("        return " + loadName + "(data)\n\n")
	b.WriteString("    @staticmethod\n")
	b.WriteString("    def load_from(read_bytes: Callable[[str], bytes | bytearray | memoryview]) -> \"" + tableName + "\":\n")
	b.WriteString("        return " + loadName + "_from(read_bytes)\n\n\n")

	b.WriteString("def " + loadName + "(data: bytes | bytearray | memoryview) -> " + tableName + ":\n")
	b.WriteString("    reader = IotaBytesReader(data)\n")
	b.WriteString("    reader.expect_magic()\n")
	b.WriteString("    version = reader.read_var_uint64()\n")
	b.WriteString(fmt.Sprintf("    if version != %d:\n", constants.BytesFormatVersion))
	b.WriteString("        raise ValueError(\"Unsupported iotaexcel bytes version.\")\n")
	b.WriteString("    reader.read_string()\n")
	b.WriteString("    reader.read_var_uint64()\n")
	b.WriteString("    self_describing = reader.read_var_uint64() != 0\n")
	b.WriteString("    field_count = reader.read_var_uint64()\n")
	b.WriteString("    for _ in range(field_count):\n")
	b.WriteString("        reader.read_var_uint64()\n")
	b.WriteString("        if self_describing:\n")
	b.WriteString("            reader.read_string()\n")
	b.WriteString("            reader.read_string()\n")
	b.WriteString("            reader.read_var_uint64()\n")
	b.WriteString("    row_count = reader.read_var_uint64()\n")
	b.WriteString("    rows: dict[" + keyTypeName + ", " + typeName + "] = {}\n")
	for _, field := range uniqueFields {
		b.WriteString("    " + uniqueIndexName(field) + ": dict[" + pythonType(field.Type) + ", " + typeName + "] = {}\n")
	}
	b.WriteString("    for _ in range(row_count):\n")
	b.WriteString("        row_reader = IotaBytesReader(reader.read_bytes())\n")
	b.WriteString("        row = " + typeName + "()\n")
	b.WriteString("        while not row_reader.end():\n")
	b.WriteString("            tag = row_reader.read_var_uint64()\n")
	b.WriteString("            field_no = tag >> 3\n")
	b.WriteString("            wire_type = tag & 7\n")
	b.WriteString("            if False:\n")
	b.WriteString("                pass\n")
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		b.WriteString("            elif field_no == " + fmt.Sprint(field.FieldNo) + ":\n")
		b.WriteString("                row." + field.Name + " = " + pythonReadExpr(field.Type, "row_reader") + "\n")
	}
	b.WriteString("            else:\n")
	b.WriteString("                row_reader.skip(wire_type)\n")
	b.WriteString("        rows[row." + keyName(sheet) + "] = row\n")
	for _, field := range uniqueFields {
		if cond := pythonUniqueIndexCondition(field); cond != "" {
			b.WriteString("        if " + cond + ":\n")
			b.WriteString("            " + uniqueIndexName(field) + "[row." + field.Name + "] = row\n")
		} else {
			b.WriteString("        " + uniqueIndexName(field) + "[row." + field.Name + "] = row\n")
		}
	}
	b.WriteString("    return " + tableName + "(rows")
	for _, field := range uniqueFields {
		b.WriteString(", " + uniqueIndexName(field))
	}
	b.WriteString(")\n\n\n")
	b.WriteString("def " + loadName + "_from(read_bytes: Callable[[str], bytes | bytearray | memoryview]) -> " + tableName + ":\n")
	b.WriteString("    if read_bytes is None:\n")
	b.WriteString("        raise ValueError(\"read_bytes is None\")\n")
	b.WriteString("    return " + loadName + "(read_bytes(\"" + bytesFileName + "\"))\n\n\n")
}

func renderRuntime() string {
	var b strings.Builder
	b.WriteString("# Code generated by iotaexcel. DO NOT EDIT.\n")
	b.WriteString("# Shared .bytes runtime helper.\n\n")
	b.WriteString("from __future__ import annotations\n\n")
	b.WriteString("import struct\n\n\n")
	b.WriteString("class IotaBytesReader:\n")
	b.WriteString("    def __init__(self, data: bytes | bytearray | memoryview) -> None:\n")
	b.WriteString("        self.data = memoryview(data)\n")
	b.WriteString("        self.pos = 0\n\n")
	b.WriteString("    def end(self) -> bool:\n")
	b.WriteString("        return self.pos >= len(self.data)\n\n")
	b.WriteString("    def expect_magic(self) -> None:\n")
	b.WriteString(fmt.Sprintf("        if self.read_raw(%d) != b%q:\n", len(constants.BytesMagic), constants.BytesMagic))
	b.WriteString("            raise ValueError(\"Invalid iotaexcel magic.\")\n\n")
	b.WriteString("    def read_var_uint64(self) -> int:\n")
	b.WriteString("        result = 0\n")
	b.WriteString("        shift = 0\n")
	b.WriteString("        while True:\n")
	b.WriteString("            byte = self.read_byte()\n")
	b.WriteString("            result |= (byte & 0x7F) << shift\n")
	b.WriteString("            if (byte & 0x80) == 0:\n")
	b.WriteString("                return result\n")
	b.WriteString("            shift += 7\n")
	b.WriteString("            if shift > 63:\n")
	b.WriteString("                raise ValueError(\"Invalid varint.\")\n\n")
	b.WriteString("    def read_sint64(self) -> int:\n")
	b.WriteString("        raw = self.read_var_uint64()\n")
	b.WriteString("        return (raw >> 1) ^ -(raw & 1)\n\n")
	b.WriteString("    def read_sint32(self) -> int:\n")
	b.WriteString("        return int(self.read_sint64())\n\n")
	b.WriteString("    def read_bool(self) -> bool:\n")
	b.WriteString("        return self.read_var_uint64() != 0\n\n")
	b.WriteString("    def read_float(self) -> float:\n")
	b.WriteString("        return struct.unpack(\"<f\", self.read_raw(4))[0]\n\n")
	b.WriteString("    def read_double(self) -> float:\n")
	b.WriteString("        return struct.unpack(\"<d\", self.read_raw(8))[0]\n\n")
	b.WriteString("    def read_bytes(self) -> bytes:\n")
	b.WriteString("        return self.read_raw(self.read_var_uint64())\n\n")
	b.WriteString("    def read_string(self) -> str:\n")
	b.WriteString("        return self.read_bytes().decode(\"utf-8\")\n\n")
	b.WriteString("    def skip(self, wire_type: int) -> None:\n")
	b.WriteString("        if wire_type == 0:\n")
	b.WriteString("            self.read_var_uint64()\n")
	b.WriteString("        elif wire_type == 1:\n")
	b.WriteString("            self.read_raw(8)\n")
	b.WriteString("        elif wire_type == 2:\n")
	b.WriteString("            self.read_bytes()\n")
	b.WriteString("        elif wire_type == 5:\n")
	b.WriteString("            self.read_raw(4)\n")
	b.WriteString("        else:\n")
	b.WriteString("            raise ValueError(\"Unsupported wire type.\")\n\n")
	b.WriteString("    def read_byte(self) -> int:\n")
	b.WriteString("        self.ensure(1)\n")
	b.WriteString("        value = self.data[self.pos]\n")
	b.WriteString("        self.pos += 1\n")
	b.WriteString("        return int(value)\n\n")
	b.WriteString("    def read_raw(self, size: int) -> bytes:\n")
	b.WriteString("        self.ensure(size)\n")
	b.WriteString("        out = self.data[self.pos:self.pos + size].tobytes()\n")
	b.WriteString("        self.pos += size\n")
	b.WriteString("        return out\n\n")
	b.WriteString("    def ensure(self, size: int) -> None:\n")
	b.WriteString("        if size < 0 or self.pos + size > len(self.data):\n")
	b.WriteString("            raise EOFError(\"Unexpected end of iotaexcel bytes.\")\n\n\n")
	b.WriteString("def parse_string_list(value: str) -> list[str]:\n")
	b.WriteString("    return value.split(\"|\") if value else []\n\n\n")
	b.WriteString("def parse_string_map(value: str) -> dict[str, str]:\n")
	b.WriteString("    out: dict[str, str] = {}\n")
	b.WriteString("    if not value:\n")
	b.WriteString("        return out\n")
	b.WriteString("    for entry in value.split(\"|\"):\n")
	b.WriteString("        key, sep, val = entry.partition(\":\")\n")
	b.WriteString("        if sep and key:\n")
	b.WriteString("            out[key] = val\n")
	b.WriteString("    return out\n")
	return b.String()
}

func writeRuntimeFile(path string, data []byte, overwrite bool) (bool, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if existing, err := os.ReadFile(path); err == nil {
		if string(existing) == string(data) {
			return false, nil
		}
		if !overwrite {
			return false, fmt.Errorf("output exists: %s", path)
		}
	}
	return true, os.WriteFile(path, data, 0o644)
}

func includeField(field model.Field, target string) bool {
	if field.Usage == model.UsageComment {
		return false
	}
	switch target {
	case "client":
		return field.Usage == model.UsageClient || field.Usage == model.UsageAll
	case "server":
		return field.Usage == model.UsageServer || field.Usage == model.UsageAll
	default:
		return true
	}
}

func pythonType(typ model.TypeSpec) string {
	switch typ.Kind {
	case model.TypeBool:
		return "bool"
	case model.TypeInt, model.TypeInt32, model.TypeInt64, model.TypeDateTime:
		return "int"
	case model.TypeFloat, model.TypeDouble:
		return "float"
	case model.TypeBytes:
		return "bytes"
	case model.TypeArray:
		return "list[str]"
	case model.TypeMap:
		return "dict[str, str]"
	default:
		return "str"
	}
}

func pythonReadExpr(typ model.TypeSpec, reader string) string {
	switch typ.Kind {
	case model.TypeBool:
		return reader + ".read_bool()"
	case model.TypeInt, model.TypeInt32:
		return reader + ".read_sint32()"
	case model.TypeInt64, model.TypeDateTime:
		return reader + ".read_sint64()"
	case model.TypeFloat:
		return reader + ".read_float()"
	case model.TypeDouble:
		return reader + ".read_double()"
	case model.TypeBytes:
		return reader + ".read_bytes()"
	case model.TypeArray:
		return "parse_string_list(" + reader + ".read_string())"
	case model.TypeMap:
		return "parse_string_map(" + reader + ".read_string())"
	default:
		return reader + ".read_string()"
	}
}

func pythonDefaultValue(typ model.TypeSpec) string {
	switch typ.Kind {
	case model.TypeBool:
		return "False"
	case model.TypeInt, model.TypeInt32, model.TypeInt64, model.TypeFloat, model.TypeDouble:
		return "0"
	case model.TypeDateTime:
		return "-62135596800"
	case model.TypeBytes:
		return "b\"\""
	case model.TypeArray:
		return "field(default_factory=list)"
	case model.TypeMap:
		return "field(default_factory=dict)"
	default:
		return "\"\""
	}
}

func keyField(sheet model.Sheet) model.Field {
	for _, field := range sheet.Fields {
		if field.IsKey {
			return field
		}
	}
	return model.Field{Type: model.TypeSpec{Kind: model.TypeString}}
}

func keyName(sheet model.Sheet) string {
	for _, field := range sheet.Fields {
		if field.IsKey {
			return field.Name
		}
	}
	return ""
}

func uniqueIndexFields(sheet model.Sheet, target string) []model.Field {
	fields := []model.Field{}
	for _, field := range sheet.Fields {
		if field.Unique && !field.IsKey && includeField(field, target) {
			fields = append(fields, field)
		}
	}
	return fields
}

func uniqueIndexName(field model.Field) string {
	return field.Name + "_index"
}

func pythonUniqueIndexCondition(field model.Field) string {
	if field.Type.Kind == model.TypeString && !field.Required {
		return "row." + field.Name + " != \"\""
	}
	return ""
}

func pythonMethodSuffix(name string) string {
	if name == "" {
		return "key"
	}
	return toSnakeCase(name)
}

func pythonLoadFunctionName(tableName string) string {
	return "load_" + toSnakeCase(tableName)
}

func toSnakeCase(name string) string {
	var b strings.Builder
	for i, r := range name {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		b.WriteRune(r)
	}
	return strings.ToLower(b.String())
}

func sanitizeComment(comment string) string {
	comment = strings.ReplaceAll(comment, "\r", " ")
	comment = strings.ReplaceAll(comment, "\n", " ")
	return comment
}
