// Package golang generates Go reader code from parsed Excel schemas.
package golang

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"iotaexcel/internal/constants"
	"iotaexcel/internal/model"
)

// Options controls Go code generation.
type Options struct {
	OutputDir string
	Package   string
	Target    string
	Overwrite bool
}

// Generate writes one Go config file for a workbook and one shared runtime file.
func Generate(wb model.Workbook, opts Options) ([]string, error) {
	if opts.Package == "" {
		opts.Package = constants.DefaultGoPackage
	}
	runtimeOut := filepath.Join(opts.OutputDir, constants.GeneratedGoRuntimeFileName)
	runtimeData := renderRuntime(opts)
	rel := filepath.FromSlash(wb.RelPath)
	dir := filepath.Dir(rel)
	base := strings.TrimSuffix(filepath.Base(rel), filepath.Ext(rel))
	name := base + constants.GeneratedGoConfigFileSuffix
	out := filepath.Join(opts.OutputDir, name)
	if dir != "." {
		out = filepath.Join(opts.OutputDir, dir, name)
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return nil, err
	}
	if !opts.Overwrite {
		if _, err := os.Stat(out); err == nil {
			return nil, fmt.Errorf("output exists: %s", out)
		}
	}
	data := render(wb, opts)
	runtimeWritten, err := writeRuntimeFile(runtimeOut, []byte(runtimeData), opts.Overwrite)
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(out, []byte(data), 0o644); err != nil {
		return nil, err
	}
	outputs := []string{out}
	if runtimeWritten {
		outputs = append([]string{runtimeOut}, outputs...)
	}
	return outputs, nil
}

func render(wb model.Workbook, opts Options) string {
	var b strings.Builder
	b.WriteString("// Code generated by iotaexcel. DO NOT EDIT.\n")
	b.WriteString("// Source: " + wb.RelPath + "\n\n")
	b.WriteString("package " + opts.Package + "\n\n")
	base := strings.TrimSuffix(filepath.Base(filepath.FromSlash(wb.RelPath)), filepath.Ext(wb.RelPath))
	for _, sheet := range wb.Sheets {
		renderTypes(&b, sheet, opts.Target, base)
	}
	return b.String()
}

func renderTypes(b *strings.Builder, sheet model.Sheet, target, workbookName string) {
	typeName := sheet.Name + constants.ConfigSuffix
	tableName := sheet.Name + constants.ConfigTableSuffix
	keyTypeName := goType(keyField(sheet).Type)
	keyMethodSuffix := keyMethodName(sheet)
	uniqueFields := uniqueIndexFields(sheet, target)
	bytesFileName := workbookName + "_" + sheet.Name + constants.ConfigSuffix + constants.BytesExtension

	b.WriteString("type " + typeName + " struct {\n")
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		if field.Comment != "" {
			b.WriteString("\t// " + goFieldName(field.Name) + " " + sanitizeComment(field.Comment) + "\n")
		}
		b.WriteString("\t" + goFieldName(field.Name) + " " + goType(field.Type) + "\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("type " + tableName + " struct {\n")
	b.WriteString("\tdatas map[" + keyTypeName + "]*" + typeName + "\n")
	for _, field := range uniqueFields {
		b.WriteString("\t" + uniqueIndexName(field) + " map[" + goType(field.Type) + "]*" + typeName + "\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("func (t *" + tableName + ") Datas() map[" + keyTypeName + "]*" + typeName + " {\n")
	b.WriteString("\treturn t.datas\n")
	b.WriteString("}\n\n")
	b.WriteString("func (t *" + tableName + ") TryGetBy" + keyMethodSuffix + "(key " + keyTypeName + ") (*" + typeName + ", bool) {\n")
	b.WriteString("\tvalue, ok := t.datas[key]\n")
	b.WriteString("\treturn value, ok\n")
	b.WriteString("}\n\n")
	for _, field := range uniqueFields {
		b.WriteString("func (t *" + tableName + ") TryGetBy" + field.Name + "(key " + goType(field.Type) + ") (*" + typeName + ", bool) {\n")
		b.WriteString("\tvalue, ok := t." + uniqueIndexName(field) + "[key]\n")
		b.WriteString("\treturn value, ok\n")
		b.WriteString("}\n\n")
	}

	b.WriteString("func Load" + tableName + "(data []byte) (*" + tableName + ", error) {\n")
	b.WriteString("\treader := newIotaBytesReader(data)\n")
	b.WriteString("\tif err := reader.expectMagic(); err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tversion, err := reader.readVarUint64()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n")
	b.WriteString(fmt.Sprintf("\tif version != %d {\n", constants.BytesFormatVersion))
	b.WriteString("\t\treturn nil, errUnsupportedIotaBytesVersion\n")
	b.WriteString("\t}\n")
	b.WriteString("\t_, err = reader.readString()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\t_, err = reader.readVarUint64()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tselfDescribing, err := reader.readVarUint64()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tfieldCount, err := reader.readVarUint64()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tfor i := uint64(0); i < fieldCount; i++ {\n")
	b.WriteString("\t\tif _, err := reader.readVarUint64(); err != nil {\n")
	b.WriteString("\t\t\treturn nil, err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tif selfDescribing != 0 {\n")
	b.WriteString("\t\t\tif _, err := reader.readString(); err != nil {\n")
	b.WriteString("\t\t\t\treturn nil, err\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tif _, err := reader.readString(); err != nil {\n")
	b.WriteString("\t\t\t\treturn nil, err\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\trowCount, err := reader.readVarUint64()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\trows := make(map[" + keyTypeName + "]*" + typeName + ", rowCount)\n")
	for _, field := range uniqueFields {
		b.WriteString("\t" + uniqueIndexName(field) + " := make(map[" + goType(field.Type) + "]*" + typeName + ", rowCount)\n")
	}
	b.WriteString("\tfor i := uint64(0); i < rowCount; i++ {\n")
	b.WriteString("\t\trowData, err := reader.readBytes()\n")
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\treturn nil, err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\trowReader := newIotaBytesReader(rowData)\n")
	b.WriteString("\t\trow := &" + typeName + "{}\n")
	b.WriteString("\t\tfor !rowReader.end() {\n")
	b.WriteString("\t\t\ttag, err := rowReader.readVarUint64()\n")
	b.WriteString("\t\t\tif err != nil {\n")
	b.WriteString("\t\t\t\treturn nil, err\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tfieldNo := tag >> 3\n")
	b.WriteString("\t\t\twireType := tag & 7\n")
	b.WriteString("\t\t\tswitch fieldNo {\n")
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		b.WriteString("\t\t\tcase " + fmt.Sprint(field.FieldNo) + ":\n")
		b.WriteString("\t\t\t\tvalue, err := " + goReadExpr(field.Type, "rowReader") + "\n")
		b.WriteString("\t\t\t\tif err != nil {\n")
		b.WriteString("\t\t\t\t\treturn nil, err\n")
		b.WriteString("\t\t\t\t}\n")
		b.WriteString("\t\t\t\trow." + goFieldName(field.Name) + " = value\n")
	}
	b.WriteString("\t\t\tdefault:\n")
	b.WriteString("\t\t\t\tif err := rowReader.skip(wireType); err != nil {\n")
	b.WriteString("\t\t\t\t\treturn nil, err\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\trows[row." + goFieldName(keyName(sheet)) + "] = row\n")
	for _, field := range uniqueFields {
		if cond := goUniqueIndexCondition(field); cond != "" {
			b.WriteString("\t\tif " + cond + " {\n")
			b.WriteString("\t\t\t" + uniqueIndexName(field) + "[row." + goFieldName(field.Name) + "] = row\n")
			b.WriteString("\t\t}\n")
		} else {
			b.WriteString("\t\t" + uniqueIndexName(field) + "[row." + goFieldName(field.Name) + "] = row\n")
		}
	}
	b.WriteString("\t}\n")
	b.WriteString("\treturn &" + tableName + "{datas: rows")
	for _, field := range uniqueFields {
		b.WriteString(", " + uniqueIndexName(field) + ": " + uniqueIndexName(field))
	}
	b.WriteString("}, nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func Load" + tableName + "From(readBytes func(string) ([]byte, error)) (*" + tableName + ", error) {\n")
	b.WriteString("\tif readBytes == nil {\n")
	b.WriteString("\t\treturn nil, errNilReadBytes\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdata, err := readBytes(\"" + bytesFileName + "\")\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn Load" + tableName + "(data)\n")
	b.WriteString("}\n\n")
}

func renderRuntime(opts Options) string {
	var b strings.Builder
	b.WriteString("// Code generated by iotaexcel. DO NOT EDIT.\n")
	b.WriteString("// Shared .bytes runtime helper.\n\n")
	b.WriteString("package " + opts.Package + "\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/binary\"\n")
	b.WriteString("\t\"errors\"\n")
	b.WriteString("\t\"io\"\n")
	b.WriteString("\t\"math\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString(")\n\n")
	b.WriteString("var errInvalidIotaBytesMagic = errors.New(\"invalid iotaexcel magic\")\n")
	b.WriteString("var errUnsupportedIotaBytesVersion = errors.New(\"unsupported iotaexcel bytes version\")\n")
	b.WriteString("var errInvalidVarint = errors.New(\"invalid varint\")\n")
	b.WriteString("var errNilReadBytes = errors.New(\"readBytes is nil\")\n\n")
	b.WriteString("type iotaBytesReader struct {\n")
	b.WriteString("\tdata []byte\n")
	b.WriteString("\tpos  int\n")
	b.WriteString("}\n\n")
	b.WriteString("func newIotaBytesReader(data []byte) *iotaBytesReader {\n")
	b.WriteString("\treturn &iotaBytesReader{data: data}\n")
	b.WriteString("}\n\n")
	b.WriteString("func (r *iotaBytesReader) end() bool {\n")
	b.WriteString("\treturn r.pos >= len(r.data)\n")
	b.WriteString("}\n\n")
	b.WriteString("func (r *iotaBytesReader) expectMagic() error {\n")
	b.WriteString(fmt.Sprintf("\tmagic, err := r.readRaw(%d)\n", len(constants.BytesMagic)))
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n")
	b.WriteString(fmt.Sprintf("\tif string(magic) != %q {\n", constants.BytesMagic))
	b.WriteString("\t\treturn errInvalidIotaBytesMagic\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func (r *iotaBytesReader) readVarUint64() (uint64, error) {\n")
	b.WriteString("\tvalue, n := binary.Uvarint(r.data[r.pos:])\n")
	b.WriteString("\tif n > 0 {\n")
	b.WriteString("\t\tr.pos += n\n")
	b.WriteString("\t\treturn value, nil\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif n == 0 {\n")
	b.WriteString("\t\treturn 0, io.ErrUnexpectedEOF\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn 0, errInvalidVarint\n")
	b.WriteString("}\n\n")
	b.WriteString("func (r *iotaBytesReader) readSInt64() (int64, error) {\n")
	b.WriteString("\traw, err := r.readVarUint64()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn 0, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn int64(raw>>1) ^ -int64(raw&1), nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func (r *iotaBytesReader) readSInt32() (int32, error) {\n")
	b.WriteString("\tvalue, err := r.readSInt64()\n")
	b.WriteString("\treturn int32(value), err\n")
	b.WriteString("}\n\n")
	b.WriteString("func (r *iotaBytesReader) readBool() (bool, error) {\n")
	b.WriteString("\tvalue, err := r.readVarUint64()\n")
	b.WriteString("\treturn value != 0, err\n")
	b.WriteString("}\n\n")
	b.WriteString("func (r *iotaBytesReader) readFloat() (float32, error) {\n")
	b.WriteString("\tdata, err := r.readRaw(4)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn 0, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn math.Float32frombits(binary.LittleEndian.Uint32(data)), nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func (r *iotaBytesReader) readDouble() (float64, error) {\n")
	b.WriteString("\tdata, err := r.readRaw(8)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn 0, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn math.Float64frombits(binary.LittleEndian.Uint64(data)), nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func (r *iotaBytesReader) readBytes() ([]byte, error) {\n")
	b.WriteString("\tsize, err := r.readVarUint64()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn r.readRaw(int(size))\n")
	b.WriteString("}\n\n")
	b.WriteString("func (r *iotaBytesReader) readString() (string, error) {\n")
	b.WriteString("\tdata, err := r.readBytes()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn \"\", err\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn string(data), nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func (r *iotaBytesReader) skip(wireType uint64) error {\n")
	b.WriteString("\tswitch wireType {\n")
	b.WriteString("\tcase 0:\n")
	b.WriteString("\t\t_, err := r.readVarUint64()\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\tcase 1:\n")
	b.WriteString("\t\t_, err := r.readRaw(8)\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\tcase 2:\n")
	b.WriteString("\t\t_, err := r.readBytes()\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\tcase 5:\n")
	b.WriteString("\t\t_, err := r.readRaw(4)\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn errors.New(\"unsupported wire type\")\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	b.WriteString("func (r *iotaBytesReader) readRaw(size int) ([]byte, error) {\n")
	b.WriteString("\tif size < 0 || r.pos+size > len(r.data) {\n")
	b.WriteString("\t\treturn nil, io.ErrUnexpectedEOF\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdata := r.data[r.pos : r.pos+size]\n")
	b.WriteString("\tr.pos += size\n")
	b.WriteString("\treturn data, nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func parseStringList(value string) []string {\n")
	b.WriteString("\tif value == \"\" {\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn strings.Split(value, \"|\")\n")
	b.WriteString("}\n\n")
	b.WriteString("func parseStringMap(value string) map[string]string {\n")
	b.WriteString("\tif value == \"\" {\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	b.WriteString("\tresult := map[string]string{}\n")
	b.WriteString("\tfor _, entry := range strings.Split(value, \"|\") {\n")
	b.WriteString("\t\tkey, val, ok := strings.Cut(entry, \":\")\n")
	b.WriteString("\t\tif !ok || key == \"\" {\n")
	b.WriteString("\t\t\tcontinue\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tresult[key] = val\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn result\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("func readStringList(reader *iotaBytesReader) ([]string, error) {\n")
	b.WriteString("\tvalue, err := reader.readString()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn parseStringList(value), nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func readStringMap(reader *iotaBytesReader) (map[string]string, error) {\n")
	b.WriteString("\tvalue, err := reader.readString()\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn parseStringMap(value), nil\n")
	b.WriteString("}\n")
	return b.String()
}

func writeRuntimeFile(path string, data []byte, overwrite bool) (bool, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if existing, err := os.ReadFile(path); err == nil {
		if string(existing) == string(data) {
			return false, nil
		}
		if !overwrite {
			return false, fmt.Errorf("output exists: %s", path)
		}
	}
	return true, os.WriteFile(path, data, 0o644)
}

func includeField(field model.Field, target string) bool {
	if field.Usage == model.UsageComment {
		return false
	}
	switch target {
	case "client":
		return field.Usage == model.UsageClient || field.Usage == model.UsageAll
	case "server":
		return field.Usage == model.UsageServer || field.Usage == model.UsageAll
	default:
		return true
	}
}

func goType(typ model.TypeSpec) string {
	switch typ.Kind {
	case model.TypeBool:
		return "bool"
	case model.TypeInt, model.TypeInt32:
		return "int32"
	case model.TypeInt64, model.TypeDateTime:
		return "int64"
	case model.TypeFloat:
		return "float32"
	case model.TypeDouble:
		return "float64"
	case model.TypeBytes:
		return "[]byte"
	case model.TypeArray:
		return "[]string"
	case model.TypeMap:
		return "map[string]string"
	default:
		return "string"
	}
}

func goReadExpr(typ model.TypeSpec, reader string) string {
	switch typ.Kind {
	case model.TypeBool:
		return reader + ".readBool()"
	case model.TypeInt, model.TypeInt32:
		return reader + ".readSInt32()"
	case model.TypeInt64, model.TypeDateTime:
		return reader + ".readSInt64()"
	case model.TypeFloat:
		return reader + ".readFloat()"
	case model.TypeDouble:
		return reader + ".readDouble()"
	case model.TypeBytes:
		return reader + ".readBytes()"
	case model.TypeArray:
		return "readStringList(" + reader + ")"
	case model.TypeMap:
		return "readStringMap(" + reader + ")"
	default:
		return reader + ".readString()"
	}
}

func keyField(sheet model.Sheet) model.Field {
	for _, field := range sheet.Fields {
		if field.IsKey {
			return field
		}
	}
	return model.Field{Type: model.TypeSpec{Kind: model.TypeString}}
}

func keyName(sheet model.Sheet) string {
	for _, field := range sheet.Fields {
		if field.IsKey {
			return field.Name
		}
	}
	return ""
}

func keyMethodName(sheet model.Sheet) string {
	name := keyName(sheet)
	if name == "" {
		return "Key"
	}
	return name
}

func uniqueIndexFields(sheet model.Sheet, target string) []model.Field {
	fields := []model.Field{}
	for _, field := range sheet.Fields {
		if field.Unique && !field.IsKey && includeField(field, target) {
			fields = append(fields, field)
		}
	}
	return fields
}

func uniqueIndexName(field model.Field) string {
	return field.Name + "Index"
}

func goUniqueIndexCondition(field model.Field) string {
	if field.Type.Kind == model.TypeString && !field.Required {
		return "row." + goFieldName(field.Name) + " != \"\""
	}
	return ""
}

func goFieldName(name string) string {
	trimmed := strings.TrimLeft(name, "_")
	if trimmed == "" {
		return "Field"
	}
	runes := []rune(trimmed)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func sanitizeComment(comment string) string {
	comment = strings.ReplaceAll(comment, "\r", " ")
	comment = strings.ReplaceAll(comment, "\n", " ")
	return comment
}
