// Package java generates Java reader code from parsed Excel schemas.
package java

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"iotaexcel/internal/constants"
	"iotaexcel/internal/model"
)

// Options controls Java code generation.
type Options struct {
	OutputDir string
	Package   string
	Target    string
	Overwrite bool
}

// Generate writes one Java config file for a workbook and one shared runtime file.
func Generate(wb model.Workbook, opts Options) ([]string, error) {
	if opts.Package == "" {
		opts.Package = constants.DefaultJavaPackage
	}
	runtimeOut := filepath.Join(opts.OutputDir, constants.GeneratedJavaRuntimeFileName)
	runtimeData := renderRuntime(opts)
	rel := filepath.FromSlash(wb.RelPath)
	dir := filepath.Dir(rel)
	base := strings.TrimSuffix(filepath.Base(rel), filepath.Ext(rel))
	name := base + constants.GeneratedJavaConfigFileSuffix
	out := filepath.Join(opts.OutputDir, name)
	if dir != "." {
		out = filepath.Join(opts.OutputDir, dir, name)
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return nil, err
	}
	if !opts.Overwrite {
		if _, err := os.Stat(out); err == nil {
			return nil, fmt.Errorf("output exists: %s", out)
		}
	}
	data := render(wb, opts)
	runtimeWritten, err := writeRuntimeFile(runtimeOut, []byte(runtimeData), opts.Overwrite)
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(out, []byte(data), 0o644); err != nil {
		return nil, err
	}
	outputs := []string{out}
	if runtimeWritten {
		outputs = append([]string{runtimeOut}, outputs...)
	}
	return outputs, nil
}

func render(wb model.Workbook, opts Options) string {
	var b strings.Builder
	className := strings.TrimSuffix(filepath.Base(filepath.FromSlash(wb.RelPath)), filepath.Ext(wb.RelPath))
	b.WriteString("// Code generated by iotaexcel. DO NOT EDIT.\n")
	b.WriteString("// Source: " + wb.RelPath + "\n")
	if opts.Package != "" {
		b.WriteString("package " + opts.Package + ";\n\n")
	}
	b.WriteString("import java.util.ArrayList;\n")
	b.WriteString("import java.util.Collections;\n")
	b.WriteString("import java.util.HashMap;\n")
	b.WriteString("import java.util.LinkedHashMap;\n")
	b.WriteString("import java.util.List;\n")
	b.WriteString("import java.util.Map;\n\n")
	b.WriteString("public final class " + className + " {\n")
	b.WriteString("    private " + className + "() {}\n\n")
	for _, sheet := range wb.Sheets {
		renderTypes(&b, sheet, opts.Target, className)
	}
	b.WriteString("}\n")
	return b.String()
}

func renderTypes(b *strings.Builder, sheet model.Sheet, target, workbookName string) {
	typeName := sheet.Name + constants.ConfigSuffix
	tableName := sheet.Name + constants.ConfigTableSuffix
	key := keyField(sheet)
	keyTypeName := javaType(key.Type)
	keyBoxedTypeName := javaBoxedType(key.Type)
	keyMethodSuffix := keyMethodName(sheet)
	uniqueFields := uniqueIndexFields(sheet, target)
	bytesFileName := workbookName + "_" + sheet.Name + constants.ConfigSuffix + constants.BytesExtension

	b.WriteString("    public static final class " + typeName + " {\n")
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		if field.Comment != "" {
			b.WriteString("        // " + sanitizeComment(field.Comment) + "\n")
		}
		b.WriteString("        public " + javaType(field.Type) + " " + field.Name + ";\n")
	}
	b.WriteString("    }\n\n")

	b.WriteString("    public static final class " + tableName + " {\n")
	b.WriteString("        private final Map<" + keyBoxedTypeName + ", " + typeName + "> datas;\n\n")
	for _, field := range uniqueFields {
		b.WriteString("        private final Map<" + javaBoxedType(field.Type) + ", " + typeName + "> " + uniqueIndexName(field) + ";\n")
	}
	if len(uniqueFields) > 0 {
		b.WriteString("\n")
	}
	b.WriteString("        private " + tableName + "(Map<" + keyBoxedTypeName + ", " + typeName + "> datas")
	for _, field := range uniqueFields {
		b.WriteString(", Map<" + javaBoxedType(field.Type) + ", " + typeName + "> " + uniqueIndexName(field))
	}
	b.WriteString(") {\n")
	b.WriteString("            this.datas = Collections.unmodifiableMap(datas);\n")
	for _, field := range uniqueFields {
		b.WriteString("            this." + uniqueIndexName(field) + " = Collections.unmodifiableMap(" + uniqueIndexName(field) + ");\n")
	}
	b.WriteString("        }\n\n")
	b.WriteString("        public Map<" + keyBoxedTypeName + ", " + typeName + "> datas() { return datas; }\n\n")
	b.WriteString("        public " + typeName + " tryGetBy" + keyMethodSuffix + "(" + keyTypeName + " key) {\n")
	b.WriteString("            return datas.get(key);\n")
	b.WriteString("        }\n\n")
	for _, field := range uniqueFields {
		b.WriteString("        public " + typeName + " tryGetBy" + field.Name + "(" + javaType(field.Type) + " key) {\n")
		b.WriteString("            return " + uniqueIndexName(field) + ".get(key);\n")
		b.WriteString("        }\n\n")
	}
	b.WriteString("        public static " + tableName + " load(byte[] data) {\n")
	b.WriteString("            IotaExcelRuntime.Reader reader = new IotaExcelRuntime.Reader(data);\n")
	b.WriteString("            reader.expectMagic();\n")
	b.WriteString("            long version = reader.readVarUInt64();\n")
	b.WriteString(fmt.Sprintf("            if (version != %dL) {\n", constants.BytesFormatVersion))
	b.WriteString("                throw new IllegalArgumentException(\"Unsupported iotaexcel bytes version.\");\n")
	b.WriteString("            }\n")
	b.WriteString("            reader.readString();\n")
	b.WriteString("            reader.readVarUInt64();\n")
	b.WriteString("            boolean selfDescribing = reader.readVarUInt64() != 0;\n")
	b.WriteString("            long fieldCount = reader.readVarUInt64();\n")
	b.WriteString("            for (long i = 0; i < fieldCount; i++) {\n")
	b.WriteString("                reader.readVarUInt64();\n")
	b.WriteString("                if (selfDescribing) {\n")
	b.WriteString("                    reader.readString();\n")
	b.WriteString("                    reader.readString();\n")
	b.WriteString("                }\n")
	b.WriteString("            }\n")
	b.WriteString("            long rowCount = reader.readVarUInt64();\n")
	b.WriteString("            Map<" + keyBoxedTypeName + ", " + typeName + "> rows = new LinkedHashMap<>();\n")
	for _, field := range uniqueFields {
		b.WriteString("            Map<" + javaBoxedType(field.Type) + ", " + typeName + "> " + uniqueIndexName(field) + " = new LinkedHashMap<>();\n")
	}
	b.WriteString("            for (long i = 0; i < rowCount; i++) {\n")
	b.WriteString("                IotaExcelRuntime.Reader rowReader = new IotaExcelRuntime.Reader(reader.readBytes());\n")
	b.WriteString("                " + typeName + " row = new " + typeName + "();\n")
	b.WriteString("                while (!rowReader.end()) {\n")
	b.WriteString("                    long tag = rowReader.readVarUInt64();\n")
	b.WriteString("                    long fieldNo = tag >> 3;\n")
	b.WriteString("                    long wireType = tag & 7;\n")
	b.WriteString("                    switch ((int)fieldNo) {\n")
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		b.WriteString("                    case " + fmt.Sprint(field.FieldNo) + ":\n")
		b.WriteString("                        row." + field.Name + " = " + javaReadExpr(field.Type, "rowReader") + ";\n")
		b.WriteString("                        break;\n")
	}
	b.WriteString("                    default:\n")
	b.WriteString("                        rowReader.skip(wireType);\n")
	b.WriteString("                        break;\n")
	b.WriteString("                    }\n")
	b.WriteString("                }\n")
	b.WriteString("                rows.put(row." + keyName(sheet) + ", row);\n")
	for _, field := range uniqueFields {
		if cond := javaUniqueIndexCondition(field); cond != "" {
			b.WriteString("                if (" + cond + ") {\n")
			b.WriteString("                    " + uniqueIndexName(field) + ".put(row." + field.Name + ", row);\n")
			b.WriteString("                }\n")
		} else {
			b.WriteString("                " + uniqueIndexName(field) + ".put(row." + field.Name + ", row);\n")
		}
	}
	b.WriteString("            }\n")
	b.WriteString("            return new " + tableName + "(rows")
	for _, field := range uniqueFields {
		b.WriteString(", " + uniqueIndexName(field))
	}
	b.WriteString(");\n")
	b.WriteString("        }\n\n")
	b.WriteString("        public static " + tableName + " loadFrom(IotaExcelRuntime.BytesReader readBytes) throws Exception {\n")
	b.WriteString("            if (readBytes == null) {\n")
	b.WriteString("                throw new IllegalArgumentException(\"readBytes is null\");\n")
	b.WriteString("            }\n")
	b.WriteString("            return load(readBytes.read(\"" + bytesFileName + "\"));\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n\n")
}

func renderRuntime(opts Options) string {
	var b strings.Builder
	b.WriteString("// Code generated by iotaexcel. DO NOT EDIT.\n")
	b.WriteString("// Shared .bytes runtime helper.\n")
	if opts.Package != "" {
		b.WriteString("package " + opts.Package + ";\n\n")
	}
	b.WriteString("import java.nio.charset.StandardCharsets;\n")
	b.WriteString("import java.util.ArrayList;\n")
	b.WriteString("import java.util.HashMap;\n")
	b.WriteString("import java.util.List;\n")
	b.WriteString("import java.util.Map;\n\n")
	b.WriteString("public final class IotaExcelRuntime {\n")
	b.WriteString("    private IotaExcelRuntime() {}\n\n")
	b.WriteString("    @FunctionalInterface\n")
	b.WriteString("    public interface BytesReader {\n")
	b.WriteString("        byte[] read(String fileName) throws Exception;\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public static final class Reader {\n")
	b.WriteString("        private final byte[] data;\n")
	b.WriteString("        private int pos;\n\n")
	b.WriteString("        public Reader(byte[] data) { this.data = data; }\n")
	b.WriteString("        public boolean end() { return pos >= data.length; }\n\n")
	b.WriteString("        public void expectMagic() {\n")
	b.WriteString(fmt.Sprintf("            String magic = new String(readRaw(%d), StandardCharsets.US_ASCII);\n", len(constants.BytesMagic)))
	b.WriteString(fmt.Sprintf("            if (!%q.equals(magic)) {\n", constants.BytesMagic))
	b.WriteString("                throw new IllegalArgumentException(\"Invalid iotaexcel magic.\");\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n\n")
	b.WriteString("        public long readVarUInt64() {\n")
	b.WriteString("            long result = 0;\n")
	b.WriteString("            int shift = 0;\n")
	b.WriteString("            while (true) {\n")
	b.WriteString("                int b = readByte() & 0xFF;\n")
	b.WriteString("                result |= (long)(b & 0x7F) << shift;\n")
	b.WriteString("                if ((b & 0x80) == 0) return result;\n")
	b.WriteString("                shift += 7;\n")
	b.WriteString("                if (shift > 63) throw new IllegalArgumentException(\"Invalid varint.\");\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n\n")
	b.WriteString("        public long readSInt64() {\n")
	b.WriteString("            long raw = readVarUInt64();\n")
	b.WriteString("            return (raw >>> 1) ^ -(raw & 1L);\n")
	b.WriteString("        }\n")
	b.WriteString("        public int readSInt32() { return (int)readSInt64(); }\n")
	b.WriteString("        public boolean readBool() { return readVarUInt64() != 0; }\n")
	b.WriteString("        public float readFloat() { return Float.intBitsToFloat(readFixed32()); }\n")
	b.WriteString("        public double readDouble() { return Double.longBitsToDouble(readFixed64()); }\n\n")
	b.WriteString("        public byte[] readBytes() {\n")
	b.WriteString("            long size = readVarUInt64();\n")
	b.WriteString("            if (size > Integer.MAX_VALUE) throw new IllegalArgumentException(\"Length-delimited value is too large.\");\n")
	b.WriteString("            return readRaw((int)size);\n")
	b.WriteString("        }\n")
	b.WriteString("        public String readString() { return new String(readBytes(), StandardCharsets.UTF_8); }\n\n")
	b.WriteString("        public void skip(long wireType) {\n")
	b.WriteString("            switch ((int)wireType) {\n")
	b.WriteString("            case 0: readVarUInt64(); break;\n")
	b.WriteString("            case 1: readRaw(8); break;\n")
	b.WriteString("            case 2: readBytes(); break;\n")
	b.WriteString("            case 5: readRaw(4); break;\n")
	b.WriteString("            default: throw new IllegalArgumentException(\"Unsupported wire type.\");\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n\n")
	b.WriteString("        private int readFixed32() {\n")
	b.WriteString("            byte[] b = readRaw(4);\n")
	b.WriteString("            return (b[0] & 0xFF) | ((b[1] & 0xFF) << 8) | ((b[2] & 0xFF) << 16) | ((b[3] & 0xFF) << 24);\n")
	b.WriteString("        }\n")
	b.WriteString("        private long readFixed64() {\n")
	b.WriteString("            byte[] b = readRaw(8);\n")
	b.WriteString("            long out = 0;\n")
	b.WriteString("            for (int i = 0; i < 8; i++) out |= (long)(b[i] & 0xFF) << (8 * i);\n")
	b.WriteString("            return out;\n")
	b.WriteString("        }\n")
	b.WriteString("        private byte readByte() {\n")
	b.WriteString("            if (pos >= data.length) throw new IllegalArgumentException(\"Unexpected end of iotaexcel bytes.\");\n")
	b.WriteString("            return data[pos++];\n")
	b.WriteString("        }\n")
	b.WriteString("        private byte[] readRaw(int size) {\n")
	b.WriteString("            if (size < 0 || pos + size > data.length) throw new IllegalArgumentException(\"Unexpected end of iotaexcel bytes.\");\n")
	b.WriteString("            byte[] out = new byte[size];\n")
	b.WriteString("            System.arraycopy(data, pos, out, 0, size);\n")
	b.WriteString("            pos += size;\n")
	b.WriteString("            return out;\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public static List<String> parseStringList(String value) {\n")
	b.WriteString("        List<String> out = new ArrayList<>();\n")
	b.WriteString("        if (value == null || value.isEmpty()) return out;\n")
	b.WriteString("        for (String item : value.split(\"\\\\|\", -1)) out.add(item);\n")
	b.WriteString("        return out;\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public static Map<String, String> parseStringMap(String value) {\n")
	b.WriteString("        Map<String, String> out = new HashMap<>();\n")
	b.WriteString("        if (value == null || value.isEmpty()) return out;\n")
	b.WriteString("        for (String entry : value.split(\"\\\\|\", -1)) {\n")
	b.WriteString("            int index = entry.indexOf(':');\n")
	b.WriteString("            if (index > 0) out.put(entry.substring(0, index), entry.substring(index + 1));\n")
	b.WriteString("        }\n")
	b.WriteString("        return out;\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String()
}

func writeRuntimeFile(path string, data []byte, overwrite bool) (bool, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if existing, err := os.ReadFile(path); err == nil {
		if string(existing) == string(data) {
			return false, nil
		}
		if !overwrite {
			return false, fmt.Errorf("output exists: %s", path)
		}
	}
	return true, os.WriteFile(path, data, 0o644)
}

func includeField(field model.Field, target string) bool {
	if field.Usage == model.UsageComment {
		return false
	}
	switch target {
	case "client":
		return field.Usage == model.UsageClient || field.Usage == model.UsageAll
	case "server":
		return field.Usage == model.UsageServer || field.Usage == model.UsageAll
	default:
		return true
	}
}

func javaType(typ model.TypeSpec) string {
	switch typ.Kind {
	case model.TypeBool:
		return "boolean"
	case model.TypeInt, model.TypeInt32:
		return "int"
	case model.TypeInt64, model.TypeDateTime:
		return "long"
	case model.TypeFloat:
		return "float"
	case model.TypeDouble:
		return "double"
	case model.TypeBytes:
		return "byte[]"
	case model.TypeArray:
		return "List<String>"
	case model.TypeMap:
		return "Map<String, String>"
	default:
		return "String"
	}
}

func javaBoxedType(typ model.TypeSpec) string {
	switch typ.Kind {
	case model.TypeBool:
		return "Boolean"
	case model.TypeInt, model.TypeInt32:
		return "Integer"
	case model.TypeInt64, model.TypeDateTime:
		return "Long"
	case model.TypeFloat:
		return "Float"
	case model.TypeDouble:
		return "Double"
	default:
		return javaType(typ)
	}
}

func javaReadExpr(typ model.TypeSpec, reader string) string {
	switch typ.Kind {
	case model.TypeBool:
		return reader + ".readBool()"
	case model.TypeInt, model.TypeInt32:
		return reader + ".readSInt32()"
	case model.TypeInt64, model.TypeDateTime:
		return reader + ".readSInt64()"
	case model.TypeFloat:
		return reader + ".readFloat()"
	case model.TypeDouble:
		return reader + ".readDouble()"
	case model.TypeBytes:
		return reader + ".readBytes()"
	case model.TypeArray:
		return "IotaExcelRuntime.parseStringList(" + reader + ".readString())"
	case model.TypeMap:
		return "IotaExcelRuntime.parseStringMap(" + reader + ".readString())"
	default:
		return reader + ".readString()"
	}
}

func keyField(sheet model.Sheet) model.Field {
	for _, field := range sheet.Fields {
		if field.IsKey {
			return field
		}
	}
	return model.Field{Type: model.TypeSpec{Kind: model.TypeString}}
}

func keyName(sheet model.Sheet) string {
	for _, field := range sheet.Fields {
		if field.IsKey {
			return field.Name
		}
	}
	return ""
}

func keyMethodName(sheet model.Sheet) string {
	name := keyName(sheet)
	if name == "" {
		return "Key"
	}
	return name
}

func uniqueIndexFields(sheet model.Sheet, target string) []model.Field {
	fields := []model.Field{}
	for _, field := range sheet.Fields {
		if field.Unique && !field.IsKey && includeField(field, target) {
			fields = append(fields, field)
		}
	}
	return fields
}

func uniqueIndexName(field model.Field) string {
	return field.Name + "Index"
}

func javaUniqueIndexCondition(field model.Field) string {
	if field.Type.Kind == model.TypeString && !field.Required {
		return "row." + field.Name + " != null && !row." + field.Name + ".isEmpty()"
	}
	return ""
}

func sanitizeComment(comment string) string {
	comment = strings.ReplaceAll(comment, "\r", " ")
	comment = strings.ReplaceAll(comment, "\n", " ")
	return comment
}
