// Package javascript generates framework-independent JavaScript reader code from parsed Excel schemas.
package javascript

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"iotaexcel/internal/constants"
	"iotaexcel/internal/model"
)

// Options controls JavaScript code generation.
type Options struct {
	OutputDir string
	Target    string
	Overwrite bool
}

// Generate writes one ES module config file for a workbook and one shared runtime file.
func Generate(wb model.Workbook, opts Options) ([]string, error) {
	runtimeOut := filepath.Join(opts.OutputDir, constants.GeneratedJavaScriptRuntimeFileName)
	runtimeData := renderRuntime()
	rel := filepath.FromSlash(wb.RelPath)
	dir := filepath.Dir(rel)
	base := strings.TrimSuffix(filepath.Base(rel), filepath.Ext(rel))
	name := base + constants.GeneratedJavaScriptConfigFileSuffix
	out := filepath.Join(opts.OutputDir, name)
	if dir != "." {
		out = filepath.Join(opts.OutputDir, dir, name)
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return nil, err
	}
	if !opts.Overwrite {
		if _, err := os.Stat(out); err == nil {
			return nil, fmt.Errorf("output exists: %s", out)
		}
	}
	data := render(wb, opts, jsImportPath(filepath.Dir(out), runtimeOut))
	runtimeWritten, err := writeRuntimeFile(runtimeOut, []byte(runtimeData), opts.Overwrite)
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(out, []byte(data), 0o644); err != nil {
		return nil, err
	}
	outputs := []string{out}
	if runtimeWritten {
		outputs = append([]string{runtimeOut}, outputs...)
	}
	return outputs, nil
}

func render(wb model.Workbook, opts Options, runtimeImport string) string {
	var b strings.Builder
	b.WriteString("// Code generated by iotaexcel. DO NOT EDIT.\n")
	b.WriteString("// Source: " + wb.RelPath + "\n\n")
	b.WriteString("import { IotaBytesReader, parseStringList, parseStringMap } from \"" + runtimeImport + "\";\n\n")
	base := strings.TrimSuffix(filepath.Base(filepath.FromSlash(wb.RelPath)), filepath.Ext(wb.RelPath))
	for _, sheet := range wb.Sheets {
		renderTypes(&b, sheet, opts.Target, base)
	}
	return b.String()
}

func jsImportPath(fromDir, toFile string) string {
	rel, err := filepath.Rel(fromDir, toFile)
	if err != nil {
		return "./" + constants.GeneratedJavaScriptRuntimeFileName
	}
	rel = filepath.ToSlash(rel)
	if strings.HasPrefix(rel, ".") {
		return rel
	}
	return "./" + rel
}

func renderTypes(b *strings.Builder, sheet model.Sheet, target, workbookName string) {
	typeName := sheet.Name + constants.ConfigSuffix
	tableName := sheet.Name + constants.ConfigTableSuffix
	keyMethodSuffix := keyMethodName(sheet)
	uniqueFields := uniqueIndexFields(sheet, target)
	loadName := "load" + tableName
	bytesFileName := workbookName + "_" + sheet.Name + constants.ConfigSuffix + constants.BytesExtension

	b.WriteString("export class " + typeName + " {\n")
	b.WriteString("  constructor() {\n")
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		if field.Comment != "" {
			b.WriteString("    // " + sanitizeComment(field.Comment) + "\n")
		}
		b.WriteString("    this." + field.Name + " = " + jsDefaultValue(field.Type) + ";\n")
	}
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	b.WriteString("export class " + tableName + " {\n")
	b.WriteString("  constructor(datas")
	for _, field := range uniqueFields {
		b.WriteString(", " + uniqueIndexName(field))
	}
	b.WriteString(") {\n")
	b.WriteString("    this.datas = datas;\n")
	for _, field := range uniqueFields {
		b.WriteString("    this." + uniqueIndexName(field) + " = " + uniqueIndexName(field) + ";\n")
	}
	b.WriteString("  }\n\n")
	b.WriteString("  tryGetBy" + keyMethodSuffix + "(key) {\n")
	b.WriteString("    return this.datas.get(key);\n")
	b.WriteString("  }\n\n")
	for _, field := range uniqueFields {
		b.WriteString("  tryGetBy" + field.Name + "(key) {\n")
		b.WriteString("    return this." + uniqueIndexName(field) + ".get(key);\n")
		b.WriteString("  }\n\n")
	}
	b.WriteString("  static load(data) {\n")
	b.WriteString("    return " + loadName + "(data);\n")
	b.WriteString("  }\n\n")
	b.WriteString("  static async loadFrom(readBytes) {\n")
	b.WriteString("    return " + loadName + "From(readBytes);\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	b.WriteString("export function " + loadName + "(data) {\n")
	b.WriteString("  const reader = new IotaBytesReader(data);\n")
	b.WriteString("  reader.expectMagic();\n")
	b.WriteString("  const version = reader.readVarUInt64();\n")
	b.WriteString(fmt.Sprintf("  if (version !== %dn) {\n", constants.BytesFormatVersion))
	b.WriteString("    throw new Error(\"Unsupported iotaexcel bytes version.\");\n")
	b.WriteString("  }\n")
	b.WriteString("  reader.readString();\n")
	b.WriteString("  reader.readVarUInt64();\n")
	b.WriteString("  const selfDescribing = reader.readVarUInt64() !== 0n;\n")
	b.WriteString("  const fieldCount = reader.readVarUInt64();\n")
	b.WriteString("  for (let i = 0n; i < fieldCount; i++) {\n")
	b.WriteString("    reader.readVarUInt64();\n")
	b.WriteString("    if (selfDescribing) {\n")
	b.WriteString("      reader.readString();\n")
	b.WriteString("      reader.readString();\n")
	b.WriteString("      reader.readVarUInt64();\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("  const rowCount = reader.readVarUInt64();\n")
	b.WriteString("  const rows = new Map();\n")
	for _, field := range uniqueFields {
		b.WriteString("  const " + uniqueIndexName(field) + " = new Map();\n")
	}
	b.WriteString("  for (let i = 0n; i < rowCount; i++) {\n")
	b.WriteString("    const rowReader = new IotaBytesReader(reader.readBytes());\n")
	b.WriteString("    const row = new " + typeName + "();\n")
	b.WriteString("    while (!rowReader.end()) {\n")
	b.WriteString("      const tag = rowReader.readVarUInt64();\n")
	b.WriteString("      const fieldNo = Number(tag >> 3n);\n")
	b.WriteString("      const wireType = Number(tag & 7n);\n")
	b.WriteString("      switch (fieldNo) {\n")
	for _, field := range sheet.Fields {
		if !includeField(field, target) {
			continue
		}
		b.WriteString("      case " + fmt.Sprint(field.FieldNo) + ":\n")
		b.WriteString("        row." + field.Name + " = " + jsReadExpr(field.Type, "rowReader") + ";\n")
		b.WriteString("        break;\n")
	}
	b.WriteString("      default:\n")
	b.WriteString("        rowReader.skip(wireType);\n")
	b.WriteString("        break;\n")
	b.WriteString("      }\n")
	b.WriteString("    }\n")
	b.WriteString("    rows.set(row." + keyName(sheet) + ", row);\n")
	for _, field := range uniqueFields {
		if cond := jsUniqueIndexCondition(field); cond != "" {
			b.WriteString("    if (" + cond + ") {\n")
			b.WriteString("      " + uniqueIndexName(field) + ".set(row." + field.Name + ", row);\n")
			b.WriteString("    }\n")
		} else {
			b.WriteString("    " + uniqueIndexName(field) + ".set(row." + field.Name + ", row);\n")
		}
	}
	b.WriteString("  }\n")
	b.WriteString("  return new " + tableName + "(rows")
	for _, field := range uniqueFields {
		b.WriteString(", " + uniqueIndexName(field))
	}
	b.WriteString(");\n")
	b.WriteString("}\n\n")
	b.WriteString("export async function " + loadName + "From(readBytes) {\n")
	b.WriteString("  if (typeof readBytes !== \"function\") {\n")
	b.WriteString("    throw new TypeError(\"readBytes must be a function.\");\n")
	b.WriteString("  }\n")
	b.WriteString("  const data = await readBytes(\"" + bytesFileName + "\");\n")
	b.WriteString("  return " + loadName + "(data);\n")
	b.WriteString("}\n\n")
}

func renderRuntime() string {
	var b strings.Builder
	b.WriteString("// Code generated by iotaexcel. DO NOT EDIT.\n")
	b.WriteString("// Shared .bytes runtime helper.\n\n")
	b.WriteString("const textDecoder = new TextDecoder();\n\n")
	b.WriteString("export class IotaBytesReader {\n")
	b.WriteString("  constructor(data) {\n")
	b.WriteString("    if (!(data instanceof Uint8Array)) {\n")
	b.WriteString("      throw new TypeError(\"iotaexcel data must be a Uint8Array.\");\n")
	b.WriteString("    }\n")
	b.WriteString("    this.data = data;\n")
	b.WriteString("    this.view = new DataView(data.buffer, data.byteOffset, data.byteLength);\n")
	b.WriteString("    this.pos = 0;\n")
	b.WriteString("  }\n\n")
	b.WriteString("  end() { return this.pos >= this.data.length; }\n\n")
	b.WriteString("  expectMagic() {\n")
	b.WriteString(fmt.Sprintf("    const magic = this.readRaw(%d);\n", len(constants.BytesMagic)))
	b.WriteString("    const value = String.fromCharCode(...magic);\n")
	b.WriteString(fmt.Sprintf("    if (value !== %q) {\n", constants.BytesMagic))
	b.WriteString("      throw new Error(\"Invalid iotaexcel magic.\");\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n\n")
	b.WriteString("  readVarUInt64() {\n")
	b.WriteString("    let result = 0n;\n")
	b.WriteString("    let shift = 0n;\n")
	b.WriteString("    while (true) {\n")
	b.WriteString("      const byte = BigInt(this.readByte());\n")
	b.WriteString("      result |= (byte & 0x7fn) << shift;\n")
	b.WriteString("      if ((byte & 0x80n) === 0n) return result;\n")
	b.WriteString("      shift += 7n;\n")
	b.WriteString("      if (shift > 63n) throw new Error(\"Invalid varint.\");\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n\n")
	b.WriteString("  readSInt64() {\n")
	b.WriteString("    const raw = this.readVarUInt64();\n")
	b.WriteString("    return (raw >> 1n) ^ -(raw & 1n);\n")
	b.WriteString("  }\n\n")
	b.WriteString("  readSInt32() { return Number(this.readSInt64()); }\n")
	b.WriteString("  readBool() { return this.readVarUInt64() !== 0n; }\n")
	b.WriteString("  readFloat() {\n")
	b.WriteString("    this.ensure(4);\n")
	b.WriteString("    const value = this.view.getFloat32(this.pos, true);\n")
	b.WriteString("    this.pos += 4;\n")
	b.WriteString("    return value;\n")
	b.WriteString("  }\n")
	b.WriteString("  readDouble() {\n")
	b.WriteString("    this.ensure(8);\n")
	b.WriteString("    const value = this.view.getFloat64(this.pos, true);\n")
	b.WriteString("    this.pos += 8;\n")
	b.WriteString("    return value;\n")
	b.WriteString("  }\n\n")
	b.WriteString("  readBytes() {\n")
	b.WriteString("    const size = this.readVarUInt64();\n")
	b.WriteString("    if (size > BigInt(Number.MAX_SAFE_INTEGER)) throw new Error(\"Length-delimited value is too large.\");\n")
	b.WriteString("    return this.readRaw(Number(size));\n")
	b.WriteString("  }\n\n")
	b.WriteString("  readString() { return textDecoder.decode(this.readBytes()); }\n\n")
	b.WriteString("  skip(wireType) {\n")
	b.WriteString("    switch (wireType) {\n")
	b.WriteString("    case 0: this.readVarUInt64(); break;\n")
	b.WriteString("    case 1: this.readRaw(8); break;\n")
	b.WriteString("    case 2: this.readBytes(); break;\n")
	b.WriteString("    case 5: this.readRaw(4); break;\n")
	b.WriteString("    default: throw new Error(\"Unsupported wire type.\");\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n\n")
	b.WriteString("  readByte() {\n")
	b.WriteString("    this.ensure(1);\n")
	b.WriteString("    return this.data[this.pos++];\n")
	b.WriteString("  }\n\n")
	b.WriteString("  readRaw(size) {\n")
	b.WriteString("    this.ensure(size);\n")
	b.WriteString("    const out = this.data.slice(this.pos, this.pos + size);\n")
	b.WriteString("    this.pos += size;\n")
	b.WriteString("    return out;\n")
	b.WriteString("  }\n\n")
	b.WriteString("  ensure(size) {\n")
	b.WriteString("    if (size < 0 || this.pos + size > this.data.length) {\n")
	b.WriteString("      throw new Error(\"Unexpected end of iotaexcel bytes.\");\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")
	b.WriteString("export function parseStringList(value) {\n")
	b.WriteString("  return value ? value.split(\"|\") : [];\n")
	b.WriteString("}\n\n")
	b.WriteString("export function parseStringMap(value) {\n")
	b.WriteString("  const out = new Map();\n")
	b.WriteString("  if (!value) return out;\n")
	b.WriteString("  for (const entry of value.split(\"|\")) {\n")
	b.WriteString("    const index = entry.indexOf(\":\");\n")
	b.WriteString("    if (index > 0) out.set(entry.slice(0, index), entry.slice(index + 1));\n")
	b.WriteString("  }\n")
	b.WriteString("  return out;\n")
	b.WriteString("}\n")
	return b.String()
}

func writeRuntimeFile(path string, data []byte, overwrite bool) (bool, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if existing, err := os.ReadFile(path); err == nil {
		if string(existing) == string(data) {
			return false, nil
		}
		if !overwrite {
			return false, fmt.Errorf("output exists: %s", path)
		}
	}
	return true, os.WriteFile(path, data, 0o644)
}

func includeField(field model.Field, target string) bool {
	if field.Usage == model.UsageComment {
		return false
	}
	switch target {
	case "client":
		return field.Usage == model.UsageClient || field.Usage == model.UsageAll
	case "server":
		return field.Usage == model.UsageServer || field.Usage == model.UsageAll
	default:
		return true
	}
}

func jsReadExpr(typ model.TypeSpec, reader string) string {
	switch typ.Kind {
	case model.TypeBool:
		return reader + ".readBool()"
	case model.TypeInt, model.TypeInt32:
		return reader + ".readSInt32()"
	case model.TypeInt64, model.TypeDateTime:
		return reader + ".readSInt64()"
	case model.TypeFloat:
		return reader + ".readFloat()"
	case model.TypeDouble:
		return reader + ".readDouble()"
	case model.TypeBytes:
		return reader + ".readBytes()"
	case model.TypeArray:
		return "parseStringList(" + reader + ".readString())"
	case model.TypeMap:
		return "parseStringMap(" + reader + ".readString())"
	default:
		return reader + ".readString()"
	}
}

func jsDefaultValue(typ model.TypeSpec) string {
	switch typ.Kind {
	case model.TypeBool:
		return "false"
	case model.TypeInt, model.TypeInt32, model.TypeFloat, model.TypeDouble:
		return "0"
	case model.TypeInt64:
		return "0n"
	case model.TypeDateTime:
		return "-62135596800n"
	case model.TypeBytes:
		return "new Uint8Array()"
	case model.TypeArray:
		return "[]"
	case model.TypeMap:
		return "new Map()"
	default:
		return "\"\""
	}
}

func keyName(sheet model.Sheet) string {
	for _, field := range sheet.Fields {
		if field.IsKey {
			return field.Name
		}
	}
	return ""
}

func keyMethodName(sheet model.Sheet) string {
	name := keyName(sheet)
	if name == "" {
		return "Key"
	}
	return name
}

func uniqueIndexFields(sheet model.Sheet, target string) []model.Field {
	fields := []model.Field{}
	for _, field := range sheet.Fields {
		if field.Unique && !field.IsKey && includeField(field, target) {
			fields = append(fields, field)
		}
	}
	return fields
}

func uniqueIndexName(field model.Field) string {
	return field.Name + "Index"
}

func jsUniqueIndexCondition(field model.Field) string {
	if field.Type.Kind == model.TypeString && !field.Required {
		return "row." + field.Name + " !== \"\""
	}
	return ""
}

func sanitizeComment(comment string) string {
	comment = strings.ReplaceAll(comment, "\r", " ")
	comment = strings.ReplaceAll(comment, "\n", " ")
	return comment
}
